kubeshop/testkube-dashboard

- public/index.html
This PR...
- When pasting the URL link of the dashboard into any other place it will gives us a meta description `created using create-react-app` so we try to remove it and add our own name of the site `Kubtest dashboard`.
-
-
-
> Update site name when pasting the url link

- src/App.tsx
- src/index.tsx
In order to prevent the icon from refreshing, we need to place it outside of the react-query provider
This PR...
- Adding the icon in the header to launch the modal made it to shake due to that react-query provider is wrapping the component with it, so we need to place it in a higher level outside of the provider.
-
-
-
- [x ] tested locally
> Move header organism outside of the query provider

- src/components/molecules/TestsList/TestsList.tsx
This PR...
- Make table header sticked to the top when scrolling.
-
-
-
> make table header sticky

- src/components/atoms/Charts/PieChart/PieChart.tsx
This PR...
- In case of we have so many tests like `1000` or `123454` the text will go out from the chart, so we need to hide it.
- Remove the text from inside the chart.
- close https://github.com/kubeshop/testkube-dashboard/issues/144
-
-
> Remove text from inside chart

- src/components/molecules/ExecutionResultsOutputs/ExecutionResultsOutputs.styled.ts
- src/components/molecules/ExecutionResultsOutputs/ExecutionResultsOutputs.tsx
This PR...
- Disable the plain text tab when there are no steps.
-
-
-
- [ x] tested locally
> Disable plain text tab when there is none

- src/components/atoms/Modal/Modal.tsx
This PR...
- Incorrect help link in API Model Dialog: https://github.com/kubeshop/testkube/issues/1419 
- Bring up API Model "Settings"
- Ensure the "Read More" link goes to the correct page.
> Fix API help link in Modal

- .github/workflows/deployment-stage.yml
This PR added another GH workflow to build a Docker image with commit hash tag and to trigger helm-charts deployment to `Stage` cluster in `helm-charts` repo.
-
-
-
-
> Trigger deploy to stage

- src/components/molecules/ExecutionDetails/TestExecutionDetails/TestExecutionDetailsTabs.tsx
LogOutput component seems to call `${localStorage.getItem('apiEndpoint')}/executions/${executionId}/logs`, which requires execution id not execution name?
https://github.com/kubeshop/testkube-dashboard/blob/26d68454f9fae4465acfff666d6bb3a72eaa770d/src/components/molecules/LogOutput/LogOutput.tsx#L37
-
-
-
> fix: execution logs

- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsVariables/Arguments.tsx
The prettify button had too much visual weight and was positioned "wrongly" :) 
We're reducing its visual load and place it to the left side
> Fix prettify button style and position

- public/index.html
Hey,
with defer `REACT_APP_API_SERVER_ENDPOINT` was always null for me. You should be able to easily reproduce it by building the image on the main branch and running it with `REACT_APP_API_SERVER_ENDPOINT` set. It'll show you modal with empty url. Removing defer fixes it for me.
> Remove defer from env-config load

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
This PR allows running GitHub actions for PRs from forked repositories.
- Do not set `ref` manually for `actions/checkout`
- Upgrade `actions/checkout` to v3
- https://github.com/kubeshop/testkube/issues/3452
- This PR is created from the forked repository, so if GitHub Actions work - it's fine
> Allow running GitHub actions for PRs from forked repositories

- .github/workflows/lint.yml
This PR will ignore the linting job when the files are changed.
- The Lint job will be run always when changes are detected
- The Stylelint command had a typo, so it was never run
- [Linting was not performed on PR](https://github.com/kubeshop/testkube/issues/3453)
- Examples
- This PR - has no changes to the source code - linting is not running
- [`3058918a`](https://github.com/kubeshop/testkube-dashboard/pull/555/commits/3058918a2790605d9af95a8b91ef481a3eabe424) - has TS changes - linting is running
- [`9d18cda5`](https://github.com/kubeshop/testkube-dashboard/pull/555/commits/9d18cda5f0449b3b4c1b71a29f024cd4f7d23423) - has no TS changes, but the commit before has - linting is running
> Run Lint job when the files are changed

- src/components/wizards/AddTestWizard/steps/FirstStep.tsx
- Expect `selectedExecutor` to be nullish
- https://github.com/kubeshop/testkube/issues/3523
- Steps to reproduce available in the task
> fix: expect that the executor might not be selected when creating test

- src/App.tsx
- src/components/custom-antd/Modal/Modal.tsx
- src/components/molecules/LogOutput/FullscreenLogOutput/FullScreenLogOutput.tsx
- src/components/organisms/EntityList/EntityListFilters/LabelsFilter/LabelsFilter.tsx
- src/components/organisms/EntityList/EntityListFilters/StatusFilter/StatusFilter.tsx
- src/components/organisms/Sider/Sider.styled.tsx
- src/components/organisms/Sider/Sider.tsx
- Use transient prop for passing prop for `Sider` styled component
- use `open` and `onOpenChange` instead of `visible` and `onVisibleChange` for `Modal` and `Dropdown`
- Use `nodeRef` to avoid deprecated `findDOMNode` for `react-transition-group`
- https://github.com/kubeshop/testkube/issues/3509
- Run dashboard and check DevTools console. There are still some errors, but these are resolved
> Get rid of some errors in the console

- .eslintrc.js
- src/App.tsx
- src/components/molecules/EndpointModal/EndpointModal.tsx
- src/components/molecules/LogOutput/LogOutput.tsx
- src/components/organisms/EntityDetails/EntityDetailsContainer/EntityDetailsContainer.tsx
- src/components/organisms/EntityList/EntityListContent/EntityListContent.tsx
- src/components/organisms/Sider/Sider.tsx
- src/components/pages/EndpointProcessing/EndpointProcessing.tsx
- src/components/pages/Executors/ExecutorsList/ExecutorsList.tsx
- src/components/pages/GlobalSettings/General/ApiEndpoint.tsx
- src/contexts/MainContext.ts
- src/models/config.ts
- src/redux/initialState.ts
- src/redux/reducers/configSlice.ts
- src/services/apiEndpoint.spec.ts
- src/services/apiEndpoint.ts
- src/services/artifacts.ts
- src/utils/endpoint.ts
- src/utils/fetchUtils.ts
- `apiEndpoint` is taken only from `services/apiEndpoint.ts` - cached or `localStorage`
- before, depending on the function, it's been taken from `MainContext`, Redux store, or directly from `localStorage`
- Race conditions have been solved
- Before, when `apiEndpoint` query parameter was used, there was a race between setting `apiEndpoint` from query param, and saving the verified one from the `localStorage`. The query param from `apiEndpoint` was replaced, as it was saved earlier.
- Clean up the code related to the API endpoint
- Unify `EndpointModal.tsx` and `ApiEndpoint.tsx` logic
- Move `<EndpointModal>` rendering from `<Sider>` to `<App>`
- Move logic for sanity API endpoint check from `EndpointModal` to the `App` component
- Keeping that logic in the `EndpointModal` was obscure, as …
> fix: clean up API endpoint code and resolve race conditions

- src/App.styled.tsx
- src/components/organisms/Sider/Sider.styled.tsx
- make the content with flexible height instead of 100vh
- keep the sidebar fixed anyway
- https://github.com/kubeshop/testkube/issues/3539
- move cursor to the sider and scroll
> fix: allow scrolling the page content, while cursor is on sider

- src/AnalyticsProvider.tsx
- src/App.tsx
- src/components/molecules/CookiesBanner/CookiesBanner.types.ts
- Limit data sent to PostHog - the referrer and the host will not be sent, and captured text will be masked
- Initialize PostHog only when the telemetry is not disabled
- https://github.com/kubeshop/testkube/issues/3609
- To show the cookies banner: enable telemetry in the backend and delete `isGADisabled` property from `localStorage`
- See what is happening without any button clicked, or after accepting/canceling
> Don't use PostHog when telemetry is disabled, limit its data

- src/components/organisms/EntityDetails/ExecutionDetailsDrawer/ExecutionDetailsDrawer.tsx
- adds loader for the execution details drawer
- Partially https://github.com/kubeshop/testkube/issues/3627
- Open "Test" or "Test Suite" details
- Open execution - when loading for first time, it will show a loader
| <img width="1920" alt="Zrzut ekranu 2023-04-6 o 14 44 22" src="https://user-images.githubusercontent.com/3843526/230382723-bf047cd1-bf35-4a56-8b18-65925abb1b7a.png"> | <img width="1920" alt="Zrzut ekranu 2023-04-6 o 14 44 13" src="https://user-images.githubusercontent.com/3843526/230382768-efa9016b-80db-45cb-986a-a71e27fb5f02.png">| 
|-|-|
> Add loader for execution details

- src/components/molecules/LogOutput/FullscreenLogOutput/FullScreenLogOutput.tsx
- src/components/molecules/LogOutput/LogOutput.styled.tsx
- src/components/molecules/LogOutput/LogOutput.tsx
- src/components/molecules/LogOutput/utils.spec.ts
- src/components/molecules/LogOutput/utils.ts
- Add an option to show only the last lines of the log (defaults to 300)
- Partially https://github.com/kubeshop/testkube/issues/3627
- Unit tests
- Manually: open some execution details
| <img width="1920" alt="Zrzut ekranu 2023-04-6 o 14 32 35" src="https://user-images.githubusercontent.com/3843526/230379902-be70ada8-9399-45c4-b8d3-5ab028f5e320.png"> |
|-|
> feat: cut LogOutput to show only (expandable) 300 lines

- src/App.tsx
- Fix typo, to show the cookies banner when it should be visible
- https://github.com/kubeshop/testkube/issues/3609
-
-
> fix: show cookies banner when telemetry is enabled in cluster

- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/CommandAndArguments/Command.tsx
This PR...
Updated the field to not be mandatory
-
-
-
-
> Fix Dashboard - Custom container executor - command is required - can't be removed

- src/AnalyticsProvider.tsx
- Add a plugin for masking sensitive data in Twilio Segment
- Mask referrer
- *In the near future we will also need to mask the hostname, but dev environments needs to be setup properly*
- Partially: kubeshop/testkube#3612
-
-
> fix: don't send referrer to the Twilio Segment

- src/components/organisms/EntityList/EntityListContent/EntityListContent.tsx
- This change is to conform the Cloud code more to the OSS, and fix the problem that may happen in future
- When the query was not done yet (i.e. because it was skipped) and refetch was requested, it may fail synchronously
-
-
-
> fix: ignore refetching error when no initial fetching was there

- src/components/molecules/ExecutionStepsList/ExecutionStepsList.tsx
- same as in Cloud
- Part of https://github.com/kubeshop/testkube/issues/3695
-
-
> fix: make delay not clickable in execution's steps list

- src/components/custom-antd/Skeleton/Skeleton.styled.tsx
- src/components/custom-antd/Skeleton/Skeleton.tsx
- src/components/molecules/ArtifactsList/ArtifactsList.tsx
- src/components/molecules/ExecutionDetails/TestExecutionDetails/TestExecutionDetailsArtifacts.tsx
- Add more customization options to custom Skeleton
- Use Skeleton when loading artifacts, same as in Cloud
-
-
> feat: use skeleton when loading artifacts

- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsVariables/Variables.tsx
- correctly detect the initial untouched state
- align to Cloud more
- related to https://github.com/kubeshop/testkube-cloud-ui/pull/223
-
-
> fix: adjust variables list to set initial value correctly

- src/components/molecules/LabelsSelect/LabelsSelect.tsx
- typo for checking the permission in LabelsSelect
-
-
> fix: typo: labels disabled when user has permissions

- src/components/pages/Sources/SourceDetails/SourceDetails.tsx
- Typo: it was skipping getting source details when the agent was available (instead unavailable)
-
-
-
> fix: typo: cluster availability check for source details

- src/components/molecules/HelpCard/HelpCard.styled.tsx
- src/components/molecules/HelpCard/HelpCard.tsx
- add customLinkIcon to HelpCard
- while it's not used in OSS yet, it's to align OSS and Cloud implementation
-
-
> feat: add customLinkIcon to HelpCard

- src/components/organisms/EntityDetails/EntityDetailsContainer/EntityDetailsContainer.tsx
- src/components/organisms/EntityList/EntityCreationModal/TestSuiteCreationModalContent.tsx
- src/components/organisms/EntityList/EntityListContent/EntityListContent.tsx
- src/components/pages/Executors/ExecutorsList/ExecutorsList.tsx
- src/components/pages/Sources/SourcesList/SourcesList.tsx
- avoid parsing pathname (`.split('/').slice(0, 4).join('/')`)
- use absolute paths
- related to https://github.com/kubeshop/testkube-cloud-ui/pull/217
-
-
> fix: avoid parsing pathname and use absolute paths

- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsDefinition/SettingsDefinition.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsDefinition/utils.ts
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/ExecutorDefinition/ExecutorDefinition.tsx
- src/components/pages/Sources/SourceDetails/SourceSettings/Definition/SourceSettingsDefinition.tsx
- src/services/executors.ts
- src/services/sources.ts
- src/services/testSuites.ts
- src/services/tests.ts
- use RTK to unify getting resource definitions
- related to https://github.com/kubeshop/testkube-cloud-ui/pull/222
-
-
> tech: use RTK to unify getting resource definitions

- src/components/molecules/CLICommands/CLICommands.tsx
- src/components/molecules/CLICommands/CopyCommand.styled.tsx
- src/components/molecules/CLICommands/CopyCommand.tsx
- src/models/command.ts
- highlight literals in CLI command
- allow quick selection on double click
- align with Cloud version
- related to https://github.com/kubeshop/testkube-cloud-ui/pull/225
-
-
> feat: improve CopyCommand

- src/AnalyticsProvider.tsx
- src/components/atoms/Pre/Pre.tsx
- src/components/molecules/Definition/Definition.tsx
- src/components/molecules/EmptyListContent/EmptyListContent.tsx
- src/components/organisms/EntityList/EntityListContent/EntityListHeader.tsx
- src/components/organisms/PageBlueprint/PageBlueprint.tsx
- src/components/pages/ErrorBoundary/ErrorBoundaryInner.tsx
- same as in Cloud
- Part of https://github.com/kubeshop/testkube/issues/3695
-
-
> chore: use PropsWithChildren instead of manually typing `children` property

- src/services/config.ts
- src/services/executions.ts
- src/services/executors.ts
- src/services/labels.ts
- src/services/repository.ts
- src/services/sources.ts
- src/services/testSuiteExecutions.ts
- src/services/testSuites.ts
- src/services/tests.ts
- src/services/triggers.ts
- src/utils/fetchUtils.ts
- Allow providing ID Token and Base URL strategy for RTK, to align with Cloud version
- Align the code style
- Related to https://github.com/kubeshop/testkube-cloud-ui/pull/231
-
-
> chore: unify RTK implementation with Cloud version

- src/App.tsx
- src/components/pages/GlobalSettings/General/ApiEndpoint.tsx
- src/services/apiEndpoint.spec.ts
- src/services/apiEndpoint.ts
- add option to configure API endpoint mechanism, so the code may be shared between OSS and Cloud
- prioritize API Endpoint from the environment variable
- When switching between OSS and Cloud for development, `localStorage` needs to be cleared each time, while it doesn't make sense - if the env variable is set, that instance should rather be statically for this purpose
- related to https://github.com/kubeshop/testkube-cloud-ui/pull/241
-
-
> feat: use configurable API endpoint mechanism, prioritize API URL from environment variable

- src/App.tsx
- src/components/molecules/DeleteEntityModal/DeleteEntityModal.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsGeneral/Delete.tsx
- src/contexts/ModalContext.tsx
- src/contexts/index.ts
- src/models/rtk.ts
- src/utils/composeProviders.tsx
- simplify composing providers, so the Git diffs will be much smaller
- extract global modal mechanism to `ModalContext`
- use it for same feature as in Cloud version (in future it could be used in all such situations)
-
-
> feat: simplify composing providers, add ModalContext, use it same way as in Cloud

- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsGeneral/Labels.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsScheduling/Schedule.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTests/SettingsTests.tsx
Now `ConfigurationCard`s wrapped the same on OSS and Cloud.
Cloud PR: https://github.com/kubeshop/testkube-cloud-ui/pull/244
> refactor: wrapper configuration card with Form

- src/components/pages/Sources/SourcesList/SourcesList.tsx
Before: 
Now:
After merging here will be moved to Cloud
> fix: user can't open create source modal if the cluster is off

- src/AnalyticsProvider.tsx
- Stop sending the hostname to the Segment.io
- All environments that should be filtered out in our metrics, are now either deleted or have telemetry disabled, so it should be a safe change
- https://github.com/kubeshop/testkube/issues/3612
- Modify `segmentIOKey` in `AppRoot.tsx` to the valid one, hardcoded `disabled: false` in `AnalyticsProvider`, comment out condition in `analytics` memo in `AnalyticsProvider`, use the production version of `useTrackTimeAnalytics`
- Go to the "Tests" page and navigate to "Test Suites"
- See "Network" for data sent to Segment.io
-
> feat: stop sending the hostname to the Segment.io

- src/components/molecules/MetricsBarChart/MetricsBarChart.styled.tsx
- src/components/molecules/MetricsBarChart/MetricsBarChart.tsx
- src/components/molecules/MetricsBarChart/components/Chart.tsx
- Give 30px of space for axis, and detach it from scrolling
- https://github.com/kubeshop/testkube/issues/3466
-
-
> fix: show axis for executions even when there is a lot of them

- src/utils/fetchUtils.ts
- immediately calculate new RTK data
- it was applying them on a new render, which is additionally not triggered by memoized query
- https://github.com/kubeshop/testkube/issues/3776
-
-
> fix: immediately return new data from RTK

- src/utils/strings.ts
- allow dots in the k8s resource names (tested and it's supported by the API)
- https://github.com/kubeshop/testkube/issues/3816
-
-
> fix: allow dots in k8s resource names

- src/components/pages/Executors/ExecutorDetails/ExecutorDetails.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/CommandAndArguments/Arguments.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/CommandAndArguments/Command.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/ContainerImage/ContainerImagePanel.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/ContainerImage/PrivateRegistry.tsx
- src/models/executors.ts
- src/redux/reducers/executorsSlice.ts
- show the latest data in Execution Details
- avoid having separate instance for the `currentExecutor`
- make the private registry optional
- pushed to the same branch, as a change is small and has conflicts with the other feature
- https://github.com/kubeshop/testkube/issues/3831
- https://github.com/kubeshop/testkube/issues/3830
-
-
> fix: show latest data in execution details / make private registry optional

- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/General/NameNType.tsx
- delete "Save" button and "required" marks
- https://github.com/kubeshop/testkube/issues/3832
-
-
> fix: hide form from executor name & type

- nginx/nginx.conf
This PR configure nginx for IPv6 by adding the directive `listen [::]:8080`
https://github.com/kubeshop/testkube/issues/3808
> feat: add NGINX IPv6 configuration

- .github/workflows/docker-build-release.yml
- .github/workflows/docker-build-tag.yml
This PR...
Update release branch naming
-
-
-
-
> ci: rename release branch

- src/antd-theme/my-antd-theme.less
- src/components/atoms/Pre/Pre.styled.tsx
- src/components/custom-antd/Form/Form.styled.tsx
- src/components/custom-antd/Form/FormItem/FormItem.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorDetails.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/CommandAndArguments/Arguments.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/CommandAndArguments/Command.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/ContainerImage/ContainerImagePanel.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/ContainerImage/PrivateRegistry.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/General/NameNType.tsx
- src/components/pages/GlobalSettings/General/ApiEndpoint.tsx
- src/components/pages/GlobalSettings/General/ConnectCloud.tsx
- src/components/pages/GlobalSettings/General/General.tsx
- src/models/executors.ts
- src/redux/reducers/executorsSlice.ts
Now disabled button (1) looks better and consistant with `Form.Item`s, `CopyCommand` has more space for command (2) and custom `FormItem` now has more gereral styles.
For 1: <img width="661" alt="image" src="https://github.com/kubeshop/testkube-dashboard/assets/25991946/3af60d11-f5a1-42f0-a50b-4e6545625d4a">
For 2: 
Prev: 
Now:
> refactor: changed theme color and styling

- src/AppRoot.tsx
- src/contexts/ModalContext.tsx
- add `ModalOutletProvider` to automatically inject the `ModalOutlet`
-
-
-
> feat: add ModalOutletProvider to automatically inject the ModalOutlet

- Dockerfile
- nginx/nginx.conf
-
- https://github.com/kubeshop/testkube/issues/3846
-
-
> fix: enable IPv6 for nginx only when ENABLE_IPV6 is set to "true"

- Dockerfile
- nginx/nginx.conf
- `ENABLE_IPV6=true` was disabling IPv6, while `ENABLE_IPV6=false` was enabling it
- kubeshop/testkube#3846
-
-
> fix: ENABLE_IPV6 was doing the opposite

- src/AppRoot.tsx
- src/components/molecules/EndpointModal/EndpointModal.tsx
- src/components/molecules/Hint/Hint.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/ExecutionsTable/EmptyExecutionsListContent/EmptyExecutionsListContent.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsDefinition/utils.ts
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsGeneral/Timeout.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTest/Source.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTest/TestType.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTests/SettingsTests.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsVariables/Arguments.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsVariables/Variables.tsx
- src/components/organisms/EntityList/EntityCreationModal/ModalConfig.tsx
- src/components/organisms/EntityList/EntityCreationModal/TestCreationModalContent.tsx
- src/components/organisms/Sider/Sider.tsx
- src/components/pages/Executors/ExecutorsList/AddExecutorsModal.tsx
- src/components/pages/Executors/ExecutorsList/EmptyCustomExecutors.tsx
- src/components/pages/Executors/ExecutorsList/ExecutorsList.tsx
- src/components/pages/GlobalSettings/General/ApiEndpoint.tsx
- src/components/pages/GlobalSettings/General/ConnectCloud.tsx
- src/components/pages/Sources/SourcesList/AddSourceModal.tsx
- src/components/pages/Sources/SourcesList/EmptySources.tsx
- src/components/pages/Sources/SourcesList/SourcesList.tsx
- src/components/pages/Triggers/Triggers.tsx
- src/constants/entitiesConfig/EmptyEntitiesListContent/EmptyTestSuitesListContent.tsx
- src/constants/entitiesConfig/EmptyEntitiesListContent/EmptyTestsListContent.tsx
- src/constants/entitiesConfig/TestsConfig.tsx
- src/utils/externalLinks.ts
This PR...
https://github.com/kubeshop/testkube/issues/3629
- official executor links left unutilized. It makes sense to map BE response with executor links and populate them into that config
-
-
-
> Utilize external links

- public/index.html
- Set global referrer policy to `no-referrer`
- kubeshop/testkube#3612
- See AJAX requests for `Referer` header - it's not there
-
> fix: avoid sending Referer header

- scripts/env.sh
- src/AppRoot.tsx
- src/env.ts
- add `REACT_APP_DISABLE_TELEMETRY` to force disabling telemetry
- it may be used on Vercel and optionally and test environments
- kubeshop/testkube#3884
-
-
> feat: add REACT_APP_DISABLE_TELEMETRY to force disabling telemetry

- src/App.styled.tsx
- src/components/organisms/EntityList/EntityListContent/EntityListContent.styled.tsx
- src/components/organisms/Sider/Sider.styled.tsx
- src/styles/globalStyles.ts
- make the whole page scrollable, instead of containers inside
- https://github.com/kubeshop/testkube/issues/3901
- Go to "Tests"
- Scroll page
- See, that the whole body is scrollable
|<img width="1919" alt="Zrzut ekranu 2023-05-29 o 09 38 50" src="https://github.com/kubeshop/testkube-dashboard/assets/3843526/ebd7ee67-e7aa-4c53-b955-c1bb174abd23">|
|-|
> fix: make whole page scrollable

- Dockerfile
- add write permissions for `nginx.conf` in the Docker image for any user, so `envsubst` may replace it for non-root users
- kubeshop/testkube#3931
-
-
> fix: allow non-root user for the Docker image

- src/constants/config.ts
- src/env.ts
- src/overrides.ts
- More details in the kubeshop/testkube#3948 ticket
- kubeshop/testkube#3948
- https://testkube-dashboard-git-dawid-featadd-opti-844689-testkube-cloud.vercel.app/?~api_server_endpoint=https://demo.testkube.io/results/v1
- see that `https://demo.testkube.io` is used as a server, like it would be environment variable
- click on red line on top of page, to reset overrides
> feat: add overrides mechanism for testing variables

- src/components/atoms/ScrollTrigger/ScrollTrigger.spec.tsx
- src/components/atoms/ScrollTrigger/ScrollTrigger.tsx
- Simplify abstract usage of `ScrollTrigger`
- `onScroll` is not required, it will not render anything though
-
-
> feat: allow void ScrollTrigger without `onScroll` event

- src/components/organisms/EntityDetails/EntityDetailsContent/EntityDetailsContent.tsx
- src/components/organisms/EntityList/EntityListContent/EntityListContent.tsx
- src/components/organisms/PageBlueprint/PageBlueprint.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorDetails.tsx
- src/components/pages/PageMetadata.tsx
- src/components/pages/Sources/SourceDetails/SourceDetails.tsx
- add a simple wrapper for page metadata
- delete `meta[name=description]` where it was using React nodes, as it ended up with React nodes serialized as JSONs
-
-
> feat: add simple wrapper for page metadata

- src/components/molecules/EntityGrid/EntityGridItem.tsx
- src/components/molecules/EntityGrid/EntityGridItemExecutionTime.tsx
- src/components/molecules/EntityGrid/EntityGridItemPure.tsx
- src/components/molecules/LabelsList/LabelsList.tsx
- src/components/organisms/EntityList/EntityListContent/EntityListContent.tsx
- avoid nested `dataItem` / `latestExecution` in the pure component
- delete unused `useAbortAllExecutions`
- use the actual `dataTest` property instead of building it internally from the `entity`
- optimize it a little (avoid re-rendering the tooltip, labels and dates)
- add TypeScript definition
-
-
> tech: add types and cleanup a little EntityGridItem components

- src/components/molecules/SettingsLayout/SettingsLayout.tsx
- src/components/molecules/SettingsLayout/index.ts
- src/components/molecules/SettingsLeftNavigation/SettingsLeftNavigation.tsx
- src/components/molecules/index.ts
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/Settings.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/ExecutorSettings.tsx
- src/components/pages/GlobalSettings/GlobalSettings.tsx
- src/components/pages/Sources/SourceDetails/SourceSettings/SourceSettings.tsx
- src/components/pages/Triggers/TriggerDetails/TriggerSettings/TriggerSettings.tsx
- Unify all the settings with `SettingsLayout`
- It is used as self-controlled at the moment, but it supports being controlled from outside via `active`/`onChange`, so it will be easy to handle routing
- part of kubeshop/testkube#3958
-
-
> tech: unify settings pages

- src/utils/sources.ts
- Send the `content` for tests created with the `TestSource`
- kubeshop/testkube#4009
-
-
> fix: creating the test from the TestSource

- src/components/organisms/EntityDetails/EntityDetailsContainer/EntityDetailsContainer.styled.tsx
- The Entity Details are not scrollable on Cloud instance (i.e. https://testkube-cloud-fwatsy5n6-testkube-cloud.vercel.app/organization/tkcorg_9deb42dda2197657/environment/tkcenv_03e3ff499f13ccba/dashboard/tests/executions/soapui-executor-smoke/execution/6489ae1915c7e745d0e7f671)
-
-
-
> fix: make EntityDetailsContainer scrollable on Cloud

- src/AppRoot.tsx
- src/env.ts
- src/utils/anonymizeQueryString.ts
- send anonymized query string along with pathname to GA/GTM
- effect is using `pathname` only as dependency, to avoid unnecessary page views with `search` - query string is dynamically adjusted for test/test suite filters
- revert change to envs: allow providing only one key
- fix using `GTM-` tags - use different script URL
-
-
-
> fix: send anonymized query string to GA/GTM / fix: make GTM- tags working

- src/components/organisms/EntityDetails/EntityDetailsContent/ExecutionsTable/TableRow/TableRowPure.tsx
> fix: fixed the text size on TableRow for execution

- src/antd-theme/my-antd-theme.less
- src/components/organisms/EntityDetails/ExecutionDetailsDrawer/ExecutionDetailsDrawer.styled.tsx
- src/components/organisms/EntityDetails/ExecutionDetailsDrawer/ExecutionDetailsDrawer.tsx
- allow scrolling list of test suite steps (avoid `overflow: hidden`)
- overwrite Drawer styles correctly
- kubeshop/testkube#4076
- Open test suite execution with many steps ([**dev**](https://dev.testkube.io/test-suites/executions/koko/execution/64a483da17e6aa7e6ff7e5dd)
- Try to scroll
-
> fix: allow scrolling test suite steps list

- src/components/molecules/ExecutionStepsList/ExecutionStepsList.styled.tsx
- src/components/molecules/ExecutionStepsList/ExecutionStepsList.tsx
- src/components/molecules/SettingsLayout/SettingsLayout.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/EntityDetailsContent.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/Settings.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTests/SettingsTests.tsx
- src/components/pages/Tests/TestsList/TestCreationModalContent/TestCreationModalContent.tsx
- src/models/config.ts
- src/models/execution.ts
- src/redux/initialState.ts
- src/redux/reducers/configSlice.ts
- Show properly test suite steps in the Execution Details drawer
- Show a warning message on the form for editing test suite steps, redirecting to YAML edition
- https://github.com/kubeshop/testkube/issues/4139
- Check it [**here**](https://testkube-dashboard-git-dawid-fixdisplay-t-faf028-testkube-cloud.vercel.app/test-suites/executions/executor-artillery-smoke-tests?~api_server_endpoint=https://dev.testkube.io/results/v1&~crd_operator_revision=develop)
| ![screencapture-testkube-dashboard-git-dawid-fixdisplay-t-faf028-testkube-cloud-vercel-app-test-suites-executions-executor-cypress-smoke-tests-2023-07-05-18_06_55](https://github.com/kubeshop/testkube-dashboard/assets/3843526/8e3c4379-5992-4228-b4b9-bc3043035d51) | ![screencapture-testkube-dashboard-git-dawid-fixdisplay-t-faf028-testkube- …
> fix: display parallel test suite steps nicely

- package.json
- avoid absolute "/" path for files, to make <base href> working
- `<base href>` ignores absolute URLs (incl. starting with `/`), so we need to use `./` kind URLs for resources
- kubeshop/testkube#2952
-
-
> fix: avoid absolute "/" path for files, to make <base href> working

- scripts/env.sh
- src/env.ts
- src/overrides.ts
This PR simplifies the environment variables usage, so we will have to duplicate less env code between OSS and Cloud.
- simplify `env.sh` script to only pass the variables instead of JS code
- expose environment variables interface to be used for Cloud
- add `getArrayValue` helper, that reads `abc, def, xyz` environment variable as `["abc", "def", "xyz"]`
-
-
-
> feat: expose environment variables interface

- scripts/env.sh
- The recent changes to `env.sh` were not running correctly in `busybox/ash` used in `nginx:alpine` image
- The new `env.sh` will work on all terminals
-
-
-
> fix: building env variables in the Docker container

- src/utils/sources.ts
This change should fix [this](https://kubeshop.sentry.io/issues/4297803908/?project=4504718232911872&query=is%3Aunresolved&referrer=issue-stream&stream_index=1).
> fix: fixed a problem reported on sentry io

- src/components/molecules/Definition/Definition.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorDetails.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/ExecutorDefinition/ExecutorDefinition.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/ExecutorSettings.tsx
- src/components/pages/Sources/SourceDetails/SourceDetails.tsx
- src/components/pages/Sources/SourceDetails/SourceSettings/Definition/SourceSettingsDefinition.tsx
- src/components/pages/Sources/SourceDetails/SourceSettings/SourceSettings.tsx
- src/components/pages/Triggers/TriggerDetails/TriggerDetails.tsx
- src/components/pages/Triggers/TriggerDetails/TriggerSettings/Definition/Definition.tsx
- src/components/pages/Triggers/TriggerDetails/TriggerSettings/TriggerSettings.tsx
- Refetch the definition after saving
- To ensure that it will look exactly the same as from the server
- Refetch the whole resource
- Earlier, the response from `PATCH` was used, but it doesn't match the contract from `GET`, so we need to refetch it instead
- It's not that important for tests/test suites, as these are frequently updated anyway
-
- Update YAML definition
- See that page is not broken
- See that the changes are propagated to other settings (i.e. `Command & Arguments`)
-
> fix: don't break settings page after saving YAML definition

- package-lock.json
- package.json
- src/components/atoms/MonacoEditor/MonacoEditor.tsx
- src/components/molecules/Definition/Definition.tsx
- src/components/molecules/ExecutionDetails/TestSuiteExecutionDetails/TestSuiteExecutionDetailsTabs.tsx
- src/components/molecules/InlineNotification/InlineNotification.styled.tsx
- src/components/molecules/InlineNotification/InlineNotification.tsx
- src/components/molecules/InlineNotification/index.ts
- src/components/molecules/KubernetesResourceEditor/KubernetesResourceEditor.tsx
- src/components/molecules/index.ts
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTests/SettingsTests.tsx
- src/contexts/MainContext.ts
- src/hooks/useClusterVersionMatch.ts
- src/utils/testSuites.ts
- Allow passing `clusterVersion` to `MainContext`, and match it with `useClusterVersionMatch` hook
- Display Test Suite V2 Executions properly
- Display and allow editing Test Suite V2 steps
- Display alert and make the YAML definition editor read-only, when the cluster is <1.13.0
-
-
|![screencapture-localhost-3000-organization-tkcorg-539cb664a4446f37-environment-tkcenv-84019fff03aac934-dashboard-executors-container-executor-curl-2023-07-14-17_31_55](https://github.com/kubeshop/testkube-dashboard/assets/3843526/01e9388e-92a5-4f1b-b3de-8cbb3b890a7d)|
|-|
> fix: backwards compatibility for test suites V2

- scripts/inject-base-href.sh
- always use trailing slash in `<base href>`
- kubeshop/testkube#2952
-
-
> fix: always use trailing slash in <base href>

- src/store/utils.tsx
- Fix `useStoreSync` - there was React update scheduled during the React render
- Simplify `useStoreSetter` - use vanilla Zustand store, to avoid calling `setState` from inside
- It doesn't require now "magic setter" logic, it's done from outside
- Allow passing store dependencies - reinitialize the store from scratch when it has changed
- Useful, when we want to completely erase the store when a different entity is chosen
-
-
-
> fix: adjust useStoreSync, simplify useStoreSetter, allow passing store dependencies

- src/AppRoot.tsx
- src/hooks/useLastCallback.ts
- `react-router` changes the identity of `navigate` function when the location path name changes - now we will keep the always the same identity
- thanks to that, we will have less memos and effects called on route change
-
-
-
> chore: persist `navigate` function across all routes

- src/components/molecules/Definition/Definition.tsx
- src/components/molecules/DeleteEntityModal/DeleteEntityModal.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/EntityDetailsContent.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsGeneral/FailureHandling.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsGeneral/Labels.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsGeneral/NameNDescription.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsGeneral/Timeout.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsScheduling/Schedule.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTest/SettingsTest.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsVariables/Arguments.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsVariables/Variables.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/CommandAndArguments/Arguments.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/CommandAndArguments/Command.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/ContainerImage/ContainerImagePanel.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/ContainerImage/PrivateRegistry.tsx
- src/components/pages/Executors/ExecutorsList/AddExecutorsModal.tsx
- src/components/pages/Sources/SourceDetails/SourceSettings/General/Authentication.tsx
- src/components/pages/Sources/SourceDetails/SourceSettings/General/NameNUrl.tsx
- src/components/pages/Sources/SourcesList/AddSourceModal.tsx
- src/components/pages/TestSuites/TestSuitesList/TestSuiteCreationModalContent/TestSuiteCreationModalContent.tsx
- src/components/pages/Tests/TestsList/TestCreationModalContent/TestCreationModalContent.tsx
- src/components/pages/Triggers/TriggerDetails/TriggerSettings/General/Name.tsx
- src/components/pages/Triggers/TriggerDetails/TriggerSettings/TriggerAction/Action.tsx
- src/components/pages/Triggers/TriggerDetails/TriggerSettings/TriggerCondition/Condition.tsx
- src/components/pages/Triggers/TriggerDetails/TriggerSettings/TriggerCondition/ResourceCondition.tsx
- src/components/pages/Triggers/TriggersList/AddTriggerModal/AddTriggerModal.tsx
- src/utils/notification.ts
- make the `displayDefaultNotificationFlow` sync as it should be
- fix the `displayDefaultNotificationFlow` returned type, to state that it has no error
- simplify wrapping functions (`res => displayDefaultNotificationFlow(res)` => `displayDefaultNotificationFlow`)
-
-
> chore: simplify calling displayDefaultNotificationFlow

- src/components/molecules/ExecutionDetails/TestExecutionDetails/TestExecutionDetailsTabs.tsx
- src/components/molecules/LogOutput/LogOutput.tsx
- src/hooks/useScrolledToBottom.ts
- simplify and improve the `LogOutput` auto-scroll
- make the whole auto-scroll logic inside of `LogOutput`
- avoid stateful decision - base on actual render
-
-
> tech: simplify and improve the LogOutput auto-scroll

- src/components/organisms/EntityDetails/EntityDetailsContent/EntityDetailsContent.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/SummaryGrid/SummaryGrid.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/SummaryGrid/SummaryGridItem.tsx
- Improve Summary Grid
- Better performance
- Better UX, because of avoiding page jump (conditional render)
- Always show timeframe filter
- Otherwise, when the test / test suite has only executions older than 7 days we don't display at all
- part of: https://github.com/kubeshop/testkube/issues/3958
- fixes: https://github.com/kubeshop/testkube/issues/4083
-
-
> fix: improve summary grid / always show filtering by timeframe

- src/DashboardRewrite.tsx
- src/components/molecules/ExecutionStepsList/ExecutionStepsList.tsx
- src/components/molecules/RunningContext/RunningContext.tsx
- src/components/molecules/SettingsLayout/SettingsLayout.tsx
- src/components/organisms/EntityDetails/EntityDetailsContainer/EntityDetailsContainer.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/EntityDetailsContent.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/ExecutionsTable/EmptyExecutionsListContent/EmptyExecutionsListContent.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/Settings.tsx
- src/components/organisms/EntityDetails/ExecutionDetailsDrawer/ExecutionDetailsDrawerHeader.tsx
- src/components/pages/EntityDetailsBlueprintRenderer/EntityDetailsBlueprintRenderer.tsx
- src/components/pages/EntityDetailsBlueprintRenderer/index.ts
- src/components/pages/Executors/ExecutorDetails/ExecutorDetails.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/ExecutorSettings.tsx
- src/components/pages/Executors/Executors.tsx
- src/components/pages/Sources/SourceDetails/SourceDetails.tsx
- src/components/pages/Sources/SourceDetails/SourceSettings/SourceSettings.tsx
- src/components/pages/Sources/Sources.tsx
- src/components/pages/TestSuites/TestSuites.tsx
- src/components/pages/TestSuites/TestSuitesList/TestSuiteCreationModalContent/TestSuiteCreationModalContent.tsx
- src/components/pages/TestSuites/TestSuitesList/TestSuitesList.tsx
- src/components/pages/Tests/Tests.tsx
- src/components/pages/Tests/TestsList/TestCreationModalContent/TestCreationModalContent.tsx
- src/components/pages/Tests/TestsList/TestsList.tsx
- src/components/pages/Triggers/TriggerDetails/TriggerDetails.tsx
- src/components/pages/Triggers/TriggerDetails/TriggerSettings/TriggerSettings.tsx
- src/components/pages/Triggers/Triggers.tsx
- src/models/config.ts
- src/redux/initialState.ts
- src/redux/reducers/configSlice.ts
- add routing to specific tabs in the UI
- clean up routes for tests and test suites, while maintaining backwards compatibility
- kubeshop/testkube#3708
-
-
> feat: add routing to different tabs

- Dockerfile
- package-lock.json
- package.json
- src/store/utils.tsx
- Fix Zustand warning from DEV from latest Zustand version - `[DEPRECATED] Use `createWithEqualityFn` instead of `create` or use `useStoreWithEqualityFn` instead of `useStore`. They can be imported from 'zustand/traditional'.` (https://github.com/pmndrs/zustand/discussions/1937)
- Use `package-lock.json` in the Docker image
-
-
-
> fix: Zustand interface deprecation, use package-lock for Docker image

- src/components/pages/Tests/TestDetails/TestExecution/TestExecutionTabs.tsx
This PR...
Adds a fallback in the there are no logs available, but there's an error message, which can be displayed instead
e.g. [https://cloud.testkube.dev/organization/tkcorg_9deb42dda2197657/environment/tkcenv_03e[…]12.7.0-smoke/executions/64d316e7f1573b1bc249ded1/log-output](https://cloud.testkube.dev/organization/tkcorg_9deb42dda2197657/environment/tkcenv_03e3ff499f13ccba/dashboard/tests/container-executor-cypress-v12.7.0-smoke/executions/64d316e7f1573b1bc249ded1/log-output)
-
-
-
-
> fix: log error display

- src/AppRoot.tsx
- Hide the "AI Insights" tab, so we can release OSS Dashboard
- We will recover it after the AI Insights will be available on Production
-
-
-
> chore: hide AI Insights tab temporarily

- src/components/organisms/EntityDetails/EntityDetailsLayer.tsx
- Increase polling interval for entity details, as WS updates are quite stable now
- kubeshop/testkube#3701
-
-
> feat: increase details polling interval from 2s to 10s

- src/App.tsx
- src/components/molecules/LogOutput/LogOutput.tsx
- fix that fullscreen log output is covering the status bar in Cloud version
-
-
-
> fix: put FullscreenLogOutput container in context of TestkubeApp

- src/components/pages/Tests/TestDetails/TestSettings/TestSettings.tsx
- use proper mutation for updating Tests schedule
- https://github.com/kubeshop/testkube/issues/4287
-
-
> fix: "Scheduling" tab for Tests uses proper mutation now

- src/App.tsx
- src/components/pages/ClusterRequired/ClusterRequired.tsx
- src/components/pages/ClusterRequired/index.ts
- src/components/pages/Executors/ExecutorsList/ExecutorsList.tsx
- src/components/pages/Loading/Loading.tsx
- src/components/pages/Offline/Offline.styled.tsx
- src/components/pages/Offline/Offline.tsx
- src/components/pages/Offline/index.ts
- src/components/pages/Sources/SourcesList/SourcesList.tsx
- src/components/pages/TestSuites/TestSuitesList/TestSuitesList.tsx
- src/components/pages/Tests/TestsList/TestsList.tsx
- src/components/pages/Triggers/TriggersList/TriggersList.tsx
- src/components/pages/index.ts
- src/store/executors.ts
Right now, when the cluster is offline, we either throw error (like on executors) or show a loader or wrong empty page.
- Fix error thrown when there is a problem with executors retrieval
- Show nicely information that the cluster is offline
-
-
| <img width="1920" alt="Zrzut ekranu 2023-08-22 o 16 48 06" src="https://github.com/kubeshop/testkube-dashboard/assets/3843526/2cc07e7c-d30a-4ba9-bf5e-3a81ef337c6b"> |
|-|
> fix: support offline agents correctly

- src/components/molecules/ConfigurationCard/ConfigurationCard.styled.tsx
- src/components/molecules/ConfigurationCard/ConfigurationCard.tsx
- src/components/organisms/CardForm/CardForm.tsx
- add `headerAction` that is used for AI consent in Cloud
- add `onValuesChange` for `CardForm`, as it's used in Cloud
-
-
-
> fix: add missing fields for ConfigurationCard/CardForm

- src/contexts/MainContext.ts
It was used only in Cloud and has become obsolete in https://github.com/kubeshop/testkube-cloud-ui/pull/403.
- delete it
-
-
-
> chore: delete isBannerAvailable from MainContext

- src/components/atoms/UploadWithInput/UploadWithInput.tsx
- src/components/custom-antd/Upload/Upload.tsx
- Open File Browser when clicking on the file input
- kubeshop/testkube#4298
-
-
> fix: make upload button clickable as a whole

- src/DashboardRewrite.tsx
- src/components/pages/TestSuites/TestSuites.tsx
- src/components/pages/Tests/Tests.tsx
- fix URLs backwards compatibility
- `/tests/executions/<name>/[...]` was not working
-
-
-
> fix: legacy URLs for the dashboard

- src/components/atoms/CreatableMultiSelect/CreatableMultiSelect.styled.tsx
- src/components/atoms/CreatableMultiSelect/CreatableMultiSelect.tsx
- src/components/molecules/LabelsSelect/LabelsSelect.tsx
- src/components/molecules/LabelsSelect/utils.ts
- src/components/organisms/EntityDetails/Settings/SettingsGeneral/Labels.tsx
- src/components/organisms/TriggersFormItems/ActionFormItems.tsx
- src/components/organisms/TriggersFormItems/ConditionFormItems.tsx
- src/components/pages/TestSuites/TestSuitesList/TestSuiteCreationModalContent/TestSuiteCreationModalContent.tsx
- src/components/pages/Tests/TestsList/TestCreationModalContent/CreationModal.styled.tsx
- src/components/pages/Tests/TestsList/TestCreationModalContent/TestCreationForm.tsx
- src/components/pages/Triggers/TriggerDetails/TriggerDetails.tsx
- src/components/pages/Triggers/TriggerDetails/TriggerSettings/Definition/Definition.tsx
- src/components/pages/Triggers/TriggerDetails/TriggerSettings/TriggerAction/TriggerAction.tsx
- src/components/pages/Triggers/TriggerDetails/TriggerSettings/TriggerCondition/Condition.tsx
- src/components/pages/Triggers/TriggerDetails/TriggerSettings/TriggerCondition/ResourceCondition.tsx
- src/components/pages/Triggers/TriggerDetails/TriggerSettings/TriggerSettings.tsx
- src/components/pages/Triggers/TriggersList/AddTriggerModal/AddTriggerModal.tsx
- src/components/pages/Triggers/utils.ts
- src/components/pages/Webhooks/WebhookCreationModal/FirstStep.tsx
- src/components/pages/Webhooks/WebhookDetails/ConditionTab/Condition.tsx
- src/components/pages/Webhooks/WebhooksList/WebhookCard.tsx
- src/services/triggers.ts
- src/utils/selectors.ts
- fix: allow empty resource identifier for Webhooks
- show "All resources" then as a value-like placeholder
- fix: improve triggers behavior
- invalidate local cache on changes automatically (in service), same as for other resources
- tech: refactor `LabelsList`
- support passing `LabelsList` directly in `Form.Item` (use `value`/`onChange` properly)
- various small fixes required after `LabelsList` refactor
-
-
-
> fix: allow empty resource identifier for webhooks / refactor LabelsSelect / improve Triggers behavior

- src/components/atoms/CreatableMultiSelect/CreatableMultiSelect.styled.tsx
- src/components/atoms/CreatableMultiSelect/CreatableMultiSelect.tsx
- src/components/atoms/CreatableMultiSelect/CustomComponents/LabelsOption.tsx
- src/components/atoms/SplitLabelText/SplitLabelText.tsx
- src/components/molecules/LabelsSelect/LabelsSelect.tsx
- src/components/molecules/LabelsSelect/utils.ts
- Handle lack of labels
- disable duplicates in the labels combo-box
- https://github.com/kubeshop/testkube/issues/4375
- https://github.com/kubeshop/testkube/issues/4358
- Try to create tests without labels
- Try to add labels with duplicated keys
| <img width="636" alt="Zrzut ekranu 2023-09-19 o 15 32 24" src="https://github.com/kubeshop/testkube-dashboard/assets/3843526/9e89acd2-6ee1-4f52-ac0b-e9f440b6dc01"> |
|-|
> fix: handle lack of labels, avoid duplicates in the labels combo-box

- src/components/molecules/ConfigurationCard/ConfigurationCard.styled.tsx
This PR fixes footer of configuration card display on mobile.
-
-
-
-
> fix: configuration card mobile

- src/components/molecules/ArtifactsList/ArtifactsList.tsx
- src/services/artifacts.ts
- stream the download when it's possible
- earlier - it was downloading the file in background, and then returned to User full file at once
- handle errors
- earlier - it would download error response in place of artifact
- pass the `routeToRequest` to handle it better in Cloud
- so we may avoid going always to the Agent for the artifact
-
-
-
> fix: improve downloading artifacts

- src/components/molecules/CLICommands/CLICommands.tsx
- add namespace to the commands if it is different namespace than testkube
-
-
-
> fix: command args

- src/AppRoot.tsx
- src/redux/store.ts
- Reset the data cached by RTK when the API endpoint is changed
- Thanks to that, we avoid mixing data from different environments
-
-
-
> fix: reset API cache after API endpoint is changed

- src/AppRoot.tsx
- src/redux/store.ts
- reset RTK store properly
- `util.resetApiState()` is an action creator only
-
-
-
> fix: reset RTK store properly

- .github/workflows/create-release-pr.yml
- .github/workflows/release-notes-pr.yml
- .github/workflows/release-notes.yml
- Add changelog information for the PRs that are going to `main` branch
- see example comments in this PR
- Add a simple GitHub manual workflow to prepare the PR for a new release
- see example PR created: https://github.com/kubeshop/testkube-dashboard/pull/887
-
-
-
> feat: release automation

- src/components/organisms/EntityDetails/EntityDetailsLayer.tsx
- src/components/organisms/EntityList/EntityListContent/EntityListContent.tsx
- src/components/pages/Tests/TestsList/TestsList.tsx
> fix: adjust visibility and polling logic

- src/AppRoot.tsx
- Reset the Application cache too after the API endpoint is changed
-
-
-
> fix: reset Application cache after API endpoint is changed

- Dockerfile
- allow using volume for nginx configuration
- when the file-system is read-only, volume may be mount for nginx configuration
-
-
-
> fix: allow using volume for nginx configuration

- packages/web/scripts/env.sh
- the `env.sh` script was generating invalid JS, like `{REACT_APP_XYZ=abc: "abc"}`
-
-
-
> fix: REACT_APP environment variables resolution

- .codeclimate.yml
- .dockerignore
- .github/workflows/test.yml
- .gitignore
- jest.config.js
- package.json
- packages/e2e-tests/pages/CreateTriggerPage.ts
- packages/web/src/components/organisms/TriggersFormItems/ResourceTriggerSelect/ResourceTriggerSelect.tsx
- packages/web/src/components/pages/TestSuites/TestSuiteDetails/TestSuiteSettings/SettingsTests/Modals/TestModal.tsx
- improve coverage collection for global `npx jest` / `npm test` command
- `collectCoverageFrom` settings from `projects` are ignored, so need to be set on the top level
- fix E2E tests for Triggers
- add CodeClimate configuration
- set pretty loose thresholds
- send test coverage to CodeClimate
-
-
-
> fix: improve coverage collection for unit tests

- package-lock.json
- package.json
- packages/web/craco.config.js
- fix `craco.config.js` to allow using `@testkube/*` packages from monorepository
- add `npm run start:prod` command to easily test the production build
-
-
-
> fix: using mono-repository packages / feat: add start:prod NPM command

- packages/web/src/components/atoms/TestkubeTheme/AnsiClassesMapping.ts
- packages/web/src/styles/Colors.ts
> Update colors for log parsing

- packages/web/src/components/molecules/MetricsBarChart/MetricsBarChart.styled.tsx
- packages/web/src/components/molecules/MetricsBarChart/components/BarWithTooltip.tsx
- packages/web/src/components/molecules/MetricsBarChart/components/BarWithTooltipPure.tsx
- packages/web/src/components/molecules/MetricsBarChart/components/Chart.tsx
- packages/web/src/components/molecules/MetricsBarChart/utils.ts
- packages/web/src/components/organisms/EntityDetails/ExecutionDetailsLayer.tsx
- packages/web/src/components/organisms/ExecutionsTable/ExecutionsTable.tsx
- packages/web/src/components/organisms/ExecutionsTable/TableRow/TableRow.tsx
- packages/web/src/store/executionDetails.ts
- improve `ExecutionsTable`
- improve `Chart`
- improve callback to open execution by its name
- [**TKC-789**](https://linear.app/kubeshop/issue/TKC-789/%5Bui%5D-log-screen-causes-a-chrome-crash) - Log screen causes a Chrome crash
- Compare profiler information for the test with 1000+ executions, after clicking "Run" button
| Description | Screenshot |
|-|-|
| Before | <img width="902" alt="Zrzut ekranu 2023-11-8 o 09 09 10" src="https://github.com/kubeshop/testkube-dashboard/assets/3843526/288743ce-368b-4fbe-b5b5-7273fcbe5a73"> |
| After | <img width="940" alt="Zrzut ekranu 2023-11-8 o 09 32 25" src="https://github.com/kubeshop/testkube-dashboard/assets/3843526/3d2806c2-5e68-401c-a04b-667dddd7050e"> |
> [TKC-789] fix: improve Entity Details performance

- packages/web/src/hooks/useClusterVersionMatch.spec.tsx
- packages/web/src/hooks/useClusterVersionMatch.ts
- ignore commit hash for the cluster version check
- it was trying to compare commit hash with regular version using semver
-
-
-
> fix: ignore commit hash for the cluster version check

- package-lock.json
- packages/web/src/components/atoms/ExternalLink/ExternalLink.tsx
- packages/web/src/components/molecules/LabelsSelect/utils.ts
- packages/web/src/plugins/ai-insights-promo/components/AiInsightsTab.tsx
- packages/web/src/plugins/sider-support/plugin.tsx
- Run `npm audit fix` (`@babel/traverse` updated)
- Optimize regular expression
- Add `rel=noopener` for external links
-
-
-
> fix: security alerts

- packages/web/scripts/env.sh
- Sanitize quotes in `env.config.js`
Syntax error in `env-config.js`, like here because of `REACT_APP_VERCEL_GIT_COMMIT_MESSAGE`:
```js
window._env_ = {
REACT_APP_VERSION: 'dev:vercel-preview',
REACT_APP_VERCEL_GIT_COMMIT_SHA: '7a85f0bc7042c8f851a644ca2582fb2b049ef9fd',
REACT_APP_VERCEL_URL: 'testkube-cloud-czwoia4vi-testkube-cloud.vercel.app',
REACT_APP_VERCEL_ENV: 'preview',
REACT_APP_VERCEL_GIT_PREVIOUS_SHA: '',
REACT_APP_VERCEL_GIT_COMMIT_AUTHOR_LOGIN: 'haneabogdan',
REACT_APP_VERCEL_GIT_PROVIDER: 'github',
REACT_APP_VERCEL_GIT_COMMIT_AUTHOR_NAME: 'haneabogdan',
REACT_APP_DISABLE_TELEMETRY: 'true',
REACT_APP_VERCEL_GIT_REPO_OWNER: 'kubeshop',
REACT_APP_VERCEL_GIT_REPO_SLUG: 'testkube-cloud-ui',
REACT_APP_VERCEL_GIT_PULL_REQUEST_ID: '',
REACT_APP_API_SERVER_ENDPOINT: …
```
> feat: sanitize quotes in env-config.js

- packages/e2e-tests/fixtures/triggers.ts
- fix: E2E tests for Triggers in Cloud
- https://github.com/kubeshop/testkube-cloud-ui/actions/runs/6809143770/job/18519121294
```
2) [chromium] › triggers.spec.ts:15:5 › Create Trigger ───────────────────────────────────────────
Error: expect(received).toEqual(expected) // deep equality
- Expected  - 0
+ Received  + 1
@@ -10,7 +10,8 @@
"name": "non-existant-resource",
"namespace": "namespace-name",
},
"testSelector": Object {
"name": "postman-executor-smoke",
+     "namespace": "testkube",
},
}
at ../helpers/common.ts:61
[59](https://github.com/kubeshop/testkube-cloud-ui/actions/runs/6809143770/job/18519121294#step:2:60) |
[60](https://github.com/kubeshop/testkube-cloud-ui/actions/runs/6809143770/job/18519121294#step:2:61) | export function validateTrigger(triggerData: …
```
> fix: E2E tests for Triggers in Cloud

- packages/web/src/components/pages/Tests/TestDetails/TestSettings/SettingsVariables/Arguments.tsx
- packages/web/src/utils/prettifyArguments.spec.ts
- packages/web/src/utils/prettifyArguments.ts
- Move prettifying arguments helper to a separate file
- Support escaping arguments there
- Add unit tests
- Unit tests or Test Details > Arguments
-
> fix: prettifying escaped arguments

- packages/web/src/components/pages/Executors/ExecutorsList/AddExecutorsModal.tsx
- packages/web/src/components/pages/Sources/SourcesList/AddSourceModal.tsx
- packages/web/src/components/pages/Triggers/TriggersList/AddTriggerModal/AddTriggerModal.tsx
- Do not close the modal when there is an error ( on create )
- https://github.com/kubeshop/testkube/issues/4427
- Try to create a trigger with the same name as one existing
- Notice the modal won't close and the error will be shown
> fix: show modal error instead of closing modal

- packages/web/src/components/pages/Tests/TestsList/TestCreationModalContent/TestCreationForm.tsx
- packages/web/src/utils/sources.ts
- Make `Test source` input optional for container executors
- https://github.com/kubeshop/testkube/issues/3201
-
-
> feat: optional test source for container executors

- packages/web/src/components/pages/Triggers/TriggersList/AddTriggerModal/ModalFirstStep.tsx
- packages/web/src/components/pages/Webhooks/WebhookCreationModal/WebhookCreationModal.tsx
- Handle validateFields and don't crash the app on error
- https://linear.app/kubeshop/issue/TKC-863/%5Bui%5D-creating-triggerwebhook-with-empty-required-valued-would-crash
-
-
> fix: catch validate fields so app doesn't crash TKC-863

- packages/web/src/components/organisms/TriggersFormItems/ActionFormItems.tsx
- packages/web/src/components/organisms/TriggersFormItems/ConditionFormItems.tsx
- packages/web/src/components/organisms/TriggersFormItems/ResourceTriggerSelect/ResourceTriggerSelect.tsx
- Filter resources based on the action ( `run test` or `run testsuite` )
- Searchable resource selector
- Searchable K8s resource selector from conditions
- [**TKC-871:** Trigger action not filtering corresponding resources](https://linear.app/kubeshop/issue/TKC-871/%5Bui%5D-trigger-action-not-filtering-corresponding-resources)
-
-
> refactor: filter tests/testSuites based on action TKC-871

- packages/plugins/src/hooks.spec.tsx
- packages/plugins/src/hooks.ts
- packages/plugins/src/internal/PluginSlot.ts
- packages/web/src/components/pages/TestSuites/TestSuiteDetails/TestSuiteDetailsContent.tsx
- packages/web/src/components/pages/Tests/TestDetails/TestDetailsContent.tsx
- packages/web/src/plugins/tests-and-test-suites/plugin.tsx
- feat: add an option to provide base slot items for slot hooks
- which may be treated as a fallback, or just basic values
- feat: add slots for Test/Test Suite Details
-
-
-
> feat: add option to provide base slot items for slot hooks / feat: add slots for Test/Test Suite Details

- packages/web/src/components/molecules/ExecutionStepsList/ExecutionStepsList.styled.tsx
- packages/web/src/components/molecules/ExecutionStepsList/ExecutionStepsList.tsx
Issue https://github.com/kubeshop/testkube/issues/4624
- Have test suite execution step as anchor link so that people could cmd/ctrl click to open in a new tab
https://github.com/kubeshop/testkube-dashboard/assets/47887589/19b6525c-f2e8-48ea-913a-b7bb0cf8cb58
> refactor: mark execution step item as anchor link

- packages/web/src/components/molecules/Definition/Definition.tsx
- Change the Definition's form state to untouched when using a new value from back-end
-
-
-
> fix: detecting definition change

- packages/web/src/components/molecules/MessagePanel/MessagePanel.tsx
- packages/web/src/plugins/promo-banners/components/PromoBanner.tsx
- telemetry.md
- add telemetry events for the promo banners
- add IDs for the promo banners
-
-
-
> feat: add telemetry events and IDs for the promo banners

- packages/web/src/components/organisms/EntityDetails/Settings/SettingsScheduling/NextExecution.spec.tsx
- packages/web/src/components/organisms/EntityDetails/Settings/SettingsScheduling/NextExecution.tsx
- packages/web/src/components/organisms/EntityDetails/Settings/SettingsScheduling/Schedule.tsx
- fix: display next execution time for scheduled executions after time passes
- https://github.com/kubeshop/testkube/issues/4682
-
-
> fix: display next execution time for scheduled executions after time passes

- Dockerfile
- Ensure that the default `/usr/share/nginx/html` and `/etc/nginx` directories in the container are writable by any user.
- kubeshop/testkube#4690
```
docker build -t tk-dash .
docker run --rm -u 1000756000:1000756000 -p 8080:8080 tk-dash
```
The server should successfully expose on `8080` port then
-
> fix: allow running Docker with non-default user

- packages/web/src/components/molecules/MetricsBarChart/components/BarWithTooltipPure.tsx
- Alignment of executions chart bar popover 
-
Before:
After:
> fix: executions bar chart popover alignment

- packages/plugins/README.md
- packages/plugins/src/internal/PluginScope.spec.ts
- packages/plugins/src/internal/PluginScope.ts
- add `syncSubscribe()` method for plugins
- it will emit information about `sync`ed value change to all scopes
-
-
-
> feat: add syncSubscribe() method for plugins

- packages/web/src/components/molecules/LogOutput/createSearchScannerFn.ts
- fix: avoid need to use external Babel replacement in the worker function
-
-
-
> fix: avoid using external Babel replacement in the worker function

- packages/web/src/components/molecules/Console/Console.tsx
- packages/web/src/components/molecules/LogOutput/LogOutput.tsx
- packages/web/src/components/molecules/LogOutput/LogOutputPure.styled.tsx
- packages/web/src/components/molecules/LogOutput/LogOutputPure.tsx
- Scroll to middle of lines if multiple selected found
-
- Select multiple log lines
- On refresh check scroll
-
> feat: multi log line selection

- packages/web/src/components/organisms/EntityDetails/EntityDetailsHeader.tsx
- packages/web/src/components/organisms/EntityDetails/EntityDetailsLayer.tsx
- packages/web/src/components/organisms/ExecutionsTable/ExecutionsTable.tsx
- packages/web/src/store/entityDetails.ts
- Calculate the corresponding executions timestamp depending on when the latest execution happened
https://github.com/kubeshop/testkube-dashboard/assets/47887589/6c97c926-b2d9-4929-ba4e-dfde845dc696
> refactor: executions timestamp filter

- packages/web/src/components/molecules/ArtifactsList/ArtifactsList.styled.tsx
- packages/web/src/components/molecules/ArtifactsList/ArtifactsList.tsx
- packages/web/src/components/molecules/ArtifactsList/ArtifactsListItem.spec.tsx
- packages/web/src/components/pages/Tests/TestDetails/TestExecution/TestExecutionArtifacts.tsx
- packages/web/src/models/artifact.ts
This PR...
- Handle new artifacts `status` property
- If processing artifacts are found, show loading text
- Show artifact item when `status` is `ready`
> refactor: handle artifacts new status

- packages/web/src/components/molecules/Console/Console.tsx
- Render logs when switching between tabs
https://github.com/kubeshop/testkube-dashboard/assets/47887589/b97cdeb8-720a-41d1-969d-25268525b97f
> fix: logs rendering when switching drawer tabs

- packages/web/src/components/pages/Tests/TestDetails/TestSettings/SettingsVariables/Arguments.styled.tsx
- packages/web/src/components/pages/Tests/TestDetails/TestSettings/SettingsVariables/Arguments.tsx
- packages/web/src/models/execution.ts
- packages/web/src/services/executors.ts
This PR...
-
- https://github.com/kubeshop/testkube/issues/4969
-
-
> feat: arguments mode

- packages/web/src/components/organisms/TestConfigurationForm/Git/CreationFormFields.tsx
- packages/web/src/components/organisms/TestConfigurationForm/Git/SourceEditFormFields.tsx
- packages/web/src/components/pages/Sources/SourceDetails/SourceSettings/General/Authentication.tsx
- packages/web/src/components/pages/Sources/SourcesList/AddSourceModal.tsx
- packages/web/src/services/apiEndpoint.ts
- Disable `Secret Management` inputs if config option is enabled
-
-
-
> feat: [TKC-1454] disable secret management

- packages/web/src/components/molecules/LogOutput/LogOutput.tsx
- packages/web/src/components/molecules/LogOutput/LogOutputActions.tsx
- packages/web/src/components/molecules/LogOutput/LogOutputV1.tsx
- packages/web/src/components/molecules/LogOutput/LogOutputV2.styled.tsx
- packages/web/src/components/molecules/LogOutput/LogOutputV2.tsx
- packages/web/src/components/molecules/LogOutput/useLogsV2.ts
- packages/web/src/index.tsx
- packages/web/src/utils/apiInfo.ts
> feat: logs v2
