kubeshop/testkube-dashboard

- .github/workflows/deployment.yml
This PR...
- Update github secrets.
-
-
-
> Update github login credentials

- src/components/molecules/ResultsDatePicker/ResultDatePicker.tsx
This PR...
- Disable date picker from antd when there are no current tests.
-
-
-
> Disable datepicker when there is are no tests

- src/components/molecules/ResultsDatePicker/ResultDatePicker.tsx
- src/components/organisms/TestsFilters/TestsFilter.tsx
This PR...
- This PR will hide the test description after applying a filter.
-
-
-
> hide test description component after filter apply

- src/hooks/tests.ts
This PR...
-
- Allow display test without refresh and override the cache.
-
-
> Show test desciption from first usage

- src/hooks/tests.ts
This PR...
-
- Prevent re-render Collapse components when auto-refresh is enabled.
-
-
> Prevent re-rendering test description Collapse

- src/hooks/tests.ts
This PR...
-
- Fix re-render
-
-
> Prevent re-render

- src/components/molecules/TestDescription/TestDescription.styled.tsx
- src/components/molecules/TestDescription/TestDescription.tsx
> fix: improved text output styling

- test/cypress/integration/homepage.js
> updated test

- src/components/organisms/TestHeader/TestHeader.tsx
This PR...
- Remove date range from statistics page.
- closes https://github.com/kubeshop/testkube-dashboard/issues/139
-
-
> Remove date range from statistics page

- src/components/molecules/ExecutionResultsOutputs/ExecutionResultsOutputs.tsx
This PR...
- Disable artifact tab when there is any.
- closes https://github.com/kubeshop/testkube-dashboard/issues/140
-
-
> Disable artifact tabs when there is any

- src/components/atoms/Modal/Modal.tsx
This PR...
- Remove border from modal.
-
-
-
- [ x] tested locally
> Remove border from modal

- src/components/molecules/ExecutionResultsOutputs/ExecutionResultsOutputs.tsx
- src/components/molecules/Logs/Logs.tsx
- src/utils/formatDate.ts
- fixed dates 
-  added getting logs stream to Logs Output tab
-
-
-
-
> fix: fixed dates and logs streams

- .prettierrc
- package-lock.json
- package.json
- src/components/atoms/LabelledInput/LabelledInput.tsx
- src/components/atoms/Modal/Modal.tsx
- yarn.lock
- added default results endpoint
- added import order package
- fixed the app name in package.json
> feat: added default results endpoint

- src/components/pages/EndointProcessing/EndointProcessing.tsx
- src/components/pages/EndointProcessing/EnpointProcessing.styled.ts
- src/utils/routes.ts
- src/utils/strings.ts
- Improved apiEndpoint setting process
- Refactored App.tsx component
> feat: improved apiEndpoint setting process

- src/services/tests.ts
- yarn.lock
> Fixed artifacts api link

- src/App.tsx
> refactor: changed NotFound behavior

- package-lock.json
- package.json
- src/components/molecules/ExecutionResultsOutputs/ExecutionResultsOutputs.tsx
- src/components/molecules/Filters/ScriptsFilters/ScriptsFilters.tsx
- src/components/molecules/Filters/TestExecutionsFilters/TestExecutionsFilters.tsx
- src/components/molecules/Filters/TestExecutionsFilters/index.ts
- src/components/molecules/TestDetailsDrawerHeader/TestDetailsDrawerHeader.tsx
- src/components/organisms/DashboardBlueprintRenderer/DashboardBlueprintRenderer.tsx
- src/components/organisms/DashboardInfoPanel/InfoPanels/TestExecutionsInfoPanel/TestExecutionsInfoPanel.tsx
- src/components/organisms/SideBar/SideBar.tsx
- src/constants/dashboardEntities/executions.tsx
- src/constants/dashboardEntities/scripts.tsx
- src/constants/dashboardEntities/testExecutions.tsx
- src/constants/dashboardEntities/tests.tsx
- src/constants/searchParams.ts
- src/models/dashboard.ts
- src/models/testExecutions.ts
- src/redux/initialState.ts
- src/redux/reducers/testExecutionsSlice.ts
- src/redux/store.ts
- src/services/testExecutions.ts
- src/utils/externalLinks.ts
- src/utils/routes.tsx
- yarn.lock
- Added Tests Executions List entity, displayed table and some details of selected Test Execution.
- Improved DashboardBlueprint component
> feat: added Tests Executions List functionality

- src/components/molecules/ExecutionResultsOutputs/TestExecutionResultsOutputs.tsx
- src/components/organisms/DashboardInfoPanel/InfoPanels/TestExecutionsInfoPanel/TestExecutionsInfoPanel.tsx
- Removed artifacts and log output
- Fixed bug when user could not see just failed steps
> fix: fixed bug when user could not see just failed steps, removed artifacts and log output

- src/services/artifacts.ts
> fix: artifacts endpoint

- src/components/organisms/DashboardContent/DashboardFilters/DashboardFilters.tsx
- Fixed behavior when show script executions button was not showing the needed data
> fix: fixed behavior when show script executions button was not showing the needed data

- src/components/organisms/DashboardContent/DashboardFilters/DashboardFilters.styled.tsx
- src/components/organisms/DashboardContent/DashboardFilters/DashboardFilters.tsx
- Fixed filtering component style, added blocks wrapping
> fix: fixed filtering component style, added blocks wrapping

- src/components/organisms/DashboardContainer/DashboardContainer.tsx
- src/components/organisms/DashboardContent/DashboardContent.tsx
- src/components/organisms/DashboardInfoPanel/InfoPanels/TestsInfoPanel/TestsInfoPanelBlocks/TestSummaryBlock.tsx
- src/models/scripts.ts
- src/models/testExecutions.ts
- src/models/tests.ts
- src/redux/initialState.ts
- src/utils/fetchUtils.ts
- Fixed behavior when dashboard was making redundant queries to the backend
> fix: fixed behavior when dashboard was making redundant queries to the backend

- package-lock.json
- src/components/molecules/TagsFilter/AppliedTags.tsx
- src/components/molecules/TagsFilter/TagsFilter.styled.ts
- src/components/molecules/TagsFilter/TagsFilter.tsx
- src/styles/globalStyles.ts
- yarn.lock
- Displayed applied tags near Tags filter
> feat: displayed applied tags near Tags filter

- src/components/molecules/ExecutionResultsOutputs/ExecutionResultsOutputs.tsx
- src/components/organisms/DashboardContainer/DashboardContainer.tsx
- src/components/organisms/DashboardContent/DashboardContent.tsx
- src/models/executions.ts
-  Improved pending script execution displaying
> feat: improved pending script execution displaying

- src/components/organisms/DashboardContainer/DashboardContainer.tsx
- Fixed a bug when there was no pagination on Script Executions
> fix: fixed bug when there was no pagination on Script Executions

- src/assets/images/testkube-symbol-black.svg
- src/assets/images/testkube-symbol-color.svg
- src/assets/images/testkube-symbol-white.svg
- src/components/molecules/TagsFilter/TagsFilter.tsx
- src/components/organisms/DashboardContent/DashboardContent.tsx
- src/components/organisms/SideBar/SideBar.styled.tsx
- src/components/organisms/SideBar/SideBar.tsx
- Updated row keys in the table
- Adjusted dashboard settings
> feat: updated row keys in the table, adjusted dashboard settings

- src/components/organisms/DashboardContent/DashboardContent.tsx
- fixed the bug when the selected row in the table was not highlighted
> fix: fixed the bug when the selected row in the table was not highlighted

- src/components/molecules/CLICommands/CopyCommand.styled.tsx
- src/components/molecules/ExecutionDetails/ExecutionDetails.styled.ts
- src/components/molecules/LabelsFilter/LabelsFilter.styled.ts
- src/components/molecules/LabelsFilter/LabelsFilter.tsx
- src/components/molecules/StatusFilter/StatusFilter.styled.tsx
- src/components/molecules/StatusFilter/StatusFilter.tsx
- src/components/molecules/TextSearchFilter/TextSearchFilter.styled.ts
- src/components/organisms/DashboardContent/DashboardFilters/DashboardFilters.styled.tsx
- src/components/organisms/DashboardContent/DashboardFilters/DashboardFilters.tsx
- src/components/organisms/DashboardInfoPanel/DashboardInfoPanel.styled.tsx
- src/components/organisms/TestDescription/TestDescription.styled.tsx
- src/components/organisms/TestDescription/TestDescription.tsx
- src/constants/dashboardEntities/testSuites.tsx
- src/constants/dashboardEntities/tests.tsx
- src/styles/Colors.ts
This PR...
- added labels and status filters
- redesighed filters header components
- minor styyling improvements
-
-
-
> Redesigned filters for table dashboard

- src/components/organisms/DashboardInfoPanel/DashboardInfoPanelContent.tsx
- fixed a bug when app crashed after clicking on some table row
> fix: fixed a bug when app crashed after clicking on some table row

- src/components/atoms/Modal/Modal.tsx
- src/components/molecules/ExecutionDetails/ExecutionDetails.tsx
- src/components/molecules/ExecutionTableRow/ExecutionStartEndTime.tsx
- src/components/molecules/ExecutionTableRow/ExecutionTableRow.tsx
- src/components/organisms/DashboardContent/DashboardContent.styled.tsx
- src/components/organisms/DashboardContent/DashboardContent.tsx
- src/components/organisms/DashboardContent/DashboardTableRow.tsx
- src/hooks/useIsRunning.ts
- src/models/testSuites.ts
- src/models/tests.ts
- src/redux/initialState.ts
- src/redux/reducers/testSuitesSlice.ts
- src/redux/reducers/testsSlice.ts
- src/services/testSuites.ts
- src/services/tests.ts
- displayed latest execution details
> feat: displayed latest execution details

- src/components/molecules/ExecutionDetails/TestExecutionDetails/TestExecutionDetailsLogOutput.tsx
> Hotfix execution redirect failed

- src/components/molecules/ExecutionTableRow/ExecutionStartEndTime.tsx
- test/cypress/integration/homepage.js
This PR...
- fix tests
- fix date/time/duration display
-
-
-
> Fix dashboard tests

- src/components/atoms/Loader/Loader.styled.tsx
- src/redux/reducers/testSuitesSlice.ts
- src/redux/reducers/testsSlice.ts
- src/styles/globalStyles.ts
Changed latest_execution to latestExecution, changed globally antd loader color
> refactor: changed latest_execution to latestExecution, changed globally antd loader color

- src/routes/Routes.config.tsx
- removed asterisk routes handling
> refactor: removed asterisk routes handling

- src/components/organisms/DashboardInfoPanel/DashboardInfoPanel.styled.tsx
This PR...
-
- fixed info panel component
-
-
> fix: fixed info panel component

- src/components/molecules/CLICommands/CopyCommand.styled.tsx
- src/styles/Colors.ts
This PR...
- changed CLI commands colors
-
-
-
> feat: changed CLI commands colors

- src/components/organisms/DashboardContent/DashboardContent.tsx
This PR...
-
- returned get_dashboard_results ga-4 action
-
-
> fix: returned get_dashboard_results ga-4 action

- README.md
> docs: update installation command

- src/App.styled.tsx
- src/App.tsx
- src/components/molecules/CLICommands/CopyCommand.tsx
- src/components/molecules/CookiesBanner/CookiesBanner.styled.tsx
- src/components/molecules/CookiesBanner/CookiesBanner.tsx
- src/components/molecules/CookiesBanner/index.ts
- src/components/molecules/InfoPanelHeader/InfoPanelHeader.tsx
- src/components/molecules/LabelsList/LabelsList.styled.ts
- src/components/molecules/LabelsList/LabelsList.tsx
- src/components/molecules/index.ts
- src/components/organisms/DashboardContent/DashboardTableRow.tsx
- src/index.tsx
- src/models/args.ts
- src/models/assertionResult.ts
- src/models/env.ts
- src/models/execution.ts
- src/models/extendTS.ts
- src/models/labels.ts
- src/models/objectRef.ts
- src/models/param.ts
- src/models/repository.ts
- src/models/test.ts
- src/models/testSuite.ts
- src/models/testSuiteExecution.ts
- src/routes/Routes.tsx
- src/utils/fetchUtils.ts
This PR...
- refactor: tech-debt resolving
-
-
-
> refactor: tech-debt resolving

- src/components/molecules/CLICommands/CopyCommand.tsx
- src/components/molecules/ExecutionDefinition/TestExecutionDefinition/TestExecutionDefinition.tsx
- src/components/molecules/ExecutionDefinition/TestExecutionDefinition/utils.ts
- src/components/molecules/index.ts
- src/models/repository.ts
- src/models/test.ts
This PR...
- handled a couple of possible test definitions
-
-
-
> feat: handled a couple of possible test definitions

- src/components/molecules/ExecutionDefinition/TestExecutionDefinition/utils.test.ts
- src/components/molecules/ExecutionDefinition/TestExecutionDefinition/utils.ts
- src/components/organisms/DashboardInfoPanel/DashboardInfoPanel.tsx
- src/utils/strings.ts
This PR...
- tested definition utils
-
-
-
> refactor: tested definition utils

- src/components/custom-antd/Input/Input.styled.tsx
- src/components/custom-antd/Input/Input.tsx
- src/components/custom-antd/Input/index.ts
- src/components/custom-antd/index.ts
- src/components/molecules/FilterMenu/FilterMenuFooter/FilterMenuFooter.styled.tsx
- src/components/molecules/FilterMenu/FilterMenuFooter/FilterMenuFooter.tsx
- src/components/molecules/LabelsFilter/LabelsFilter.styled.ts
- src/components/molecules/LabelsFilter/LabelsFilter.tsx
- src/components/molecules/StatusFilter/StatusFilter.tsx
- src/models/testSuites.ts
- src/models/tests.ts
- src/redux/initialState.ts
This PR...
- some fixes to status filter
- added input custom antd component
- redone labels filter
Closes: https://github.com/kubeshop/testkube/issues/1279, https://github.com/kubeshop/testkube/issues/1280
-
-
-
> feat: labels filter rework

- package-lock.json
- package.json
- src/components/atoms/Modal/Modal.tsx
- src/components/molecules/ExecutionTableRow/ExecutionDuration.tsx
- src/components/organisms/DashboardInfoPanel/DashboardInfoPanelContent.tsx
- yarn.lock
This PR...
-
- fixed run button functionality
-
-
> fix: fixed run button functionality

- src/components/molecules/CLICommands/CLICommands.tsx
- src/components/molecules/CLICommands/CopyCommand.tsx
- src/components/molecules/ExecutionDefinition/TestExecutionDefinition/utils.ts
- src/components/molecules/ExecutionStepsList/ExecutionStepsList.tsx
- src/components/organisms/DashboardContainer/DashboardContainer.tsx
- src/components/organisms/DashboardContent/DashboardContent.tsx
- src/components/organisms/DashboardInfoPanel/EmptyDashboardInfoPanel.tsx
This PR...
- adjusted deep linking behavior
- added new GA event
-
-
-
> feat: adjusted deep linking behavior, added new GA event

- src/components/atoms/Modal/Modal.tsx
- src/components/custom-antd/Tooltip/Tooltip.tsx
- src/components/custom-antd/Tooltip/index.ts
- src/components/custom-antd/index.ts
- src/components/molecules/CLICommands/CopyCommand.tsx
- src/components/molecules/LabelsFilter/LabelsFilter.tsx
- src/components/molecules/LogOutput/logActions/CopyAction.tsx
- src/components/molecules/LogOutput/logActions/FullScreenAction.tsx
- src/components/organisms/SideBar/SideBar.tsx
- src/routes/Routes.tsx
- src/styles/Colors.ts
- src/styles/globalStyles.ts
- yarn.lock
This PR...
- refactored Ant Design Tooltip
-
-
-
> refactor: refactored Ant Design Tooltip

- .github/workflows/build.yml
- Dockerfile
- src/components/molecules/ExecutionDetails/TestExecutionDetails/TestExecutionDetailsTabs.tsx
- src/constants/testExecutors.ts
This PR adds artifacts to the SoapUI executions view.
I also updated the Dockerfile such that it contains the installation of chromium, otherwise it seems to fail.
-
-
-
-
> feat: add artifacts to SoapUI executions

- src/components/molecules/ExecutionDetails/TestExecutionDetails/TestExecutionDetailsLogOutput.tsx
- src/components/molecules/ExecutionStepsList/ExecutionStepsList.styled.tsx
This PR...
-
- fixed real time log output displaying, fixed hover of icon
-
-
> fix: fixed real time log output displaying, fixed hover of icon

- src/components/molecules/LogOutput/LogOutput.styled.tsx
- src/components/molecules/LogOutput/logActions/FullScreenAction.tsx
This PR...
- changed an icon and styles of log output header
-
-
-
> refactor: changed an icon and styles of log output header

- cypress/integration/Dashboard/filters.spec.ts
- src/components/molecules/LabelsFilter/LabelsFilter.tsx
- src/components/molecules/StatusFilter/StatusFilter.tsx
- src/constants/searchParams.ts
- src/models/testSuites.ts
- src/models/tests.ts
- src/redux/initialState.ts
This PR...
- filters tests
- fixed url query params
-
-
-
> filters tests

- cypress/integration/Dashboard/filters.spec.ts
> bug: fix search text test

- src/components/wizards/AddTestWizard/AddTestWizard.tsx
This PR...
-
- fixed test creation onSave function
-
-
> fix: fixed test creation onSave function

- src/components/wizards/AddTestWizard/AddTestWizard.tsx
This PR...
-
- fixed onRunClick function
-
-
> fix: fixed onRunClick function

- src/assets/images/artilleryIcon.svg
- src/components/atoms/TestRunnerIcon/TestRunnerIcon.tsx
- src/components/wizards/AddTestWizard/utils.ts
- src/constants/testExecutors.ts
- src/models/testExecutors.ts
This PR...
- added Artillery test
-
-
-
> feat: added Artillery test

- src/components/atoms/Modal/Modal.tsx
- src/components/organisms/DashboardContent/DashboardContent.tsx
This PR...
- adjusted content loading and change api endpoint behavior
-
-
-
> feat: adjusted content loading and change api endpoint behavior

- src/components/atoms/Modal/Modal.tsx
This PR...
- updated endpoint fallback
-
-
-
> feat: updated endpoint fallback

- src/components/wizards/AddTestWizard/utils.ts
This PR...
- repo path is not required
-
-
-
> feat: repo path is not required

- .github/workflows/deployment.yml
- Dockerfile
Cross build testkube dashboard so that it can be tun on both `amd` and `arm` architecture.
-
-
-
-
> Add arm image

- src/components/molecules/ExecutionDefinition/TestExecutionDefinition/TestExecutionDefinition.tsx
- src/services/tests.ts
This PR...
- implemented new CRD displaying
-
-
-
> feat: implemented new CRD displaying

- src/components/molecules/FilterMenu/FilterMenuFooter/FilterMenuFooter.styled.tsx
- src/components/molecules/FilterMenu/FilterMenuFooter/FilterMenuFooter.tsx
- src/components/molecules/FilterMenu/MenuFilter.styled.tsx
- src/components/organisms/EntityExecutions/EntityExecutionsContent/Settings/SettingsTests/SettingsTests.styled.tsx
- src/components/organisms/EntityExecutions/EntityExecutionsContent/Settings/SettingsTests/SettingsTests.tsx
- src/components/organisms/EntityList/EntityCreationModal/TestCreationModalContent.tsx
- src/components/organisms/EntityList/EntityListFilters/LabelsFilter/LabelsFilter.tsx
- src/styles/Shadows.ts
This PR...
- Removes scroll container on test suites – test list (moved the select box to the bottom)
- Adds a `Shadows.ts` file to define shadows on tooltips & popups
- Adapted filter stylings slightly
- Using the customised Button on Test Creation
-
-
> Fix stylings and minor tweaks to redesign

- src/components/molecules/Variables/VariablesDescriptions/TestSuiteDescription.tsx
- src/components/organisms/EmptyEntityListContent/EmptyEntityListContent.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/ExecutionsTable/EmptyExecutionsListContent/EmptyExecutionsListContent.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsDefinition/utils.ts
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTests/SettingsTests.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsVariables/Arguments.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsVariables/Variables.tsx
- src/components/pages/Executors/Executors.tsx
- src/components/pages/Executors/utils.ts
- src/constants/entitiesConfig/EmptyEntitiesListContent/EmptyTestSuitesListContent.tsx
- src/constants/entitiesConfig/EmptyEntitiesListContent/EmptyTestsListContent.tsx
- src/utils/externalLinks.ts
This PR...
- Updates documentation links accordingly :)
-
-
-
> docs: fix documentation links

- .github/CODEOWNERS
- Dockerfile
> feat: Testkube root-less

- Dockerfile
> fix: permissions issues

- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTests/DelayModal.tsx
- src/components/wizards/AddTestWizard/AddTestWizard.tsx
- src/hooks/useTrackTimeAnalytics.ts
> Build hotfix

- Dockerfile
> fix:remove .env reference from local

- src/components/atoms/CreatableMultiSelect/CreatableMultiSelect.tsx
- src/components/atoms/CreatableMultiSelect/CustomComponents/LabelsMultiValueLabel.tsx
- src/components/atoms/CreatableMultiSelect/CustomComponents/LabelsOption.tsx
- src/components/molecules/LabelsSelect/LabelsSelect.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/EntityDetailsContent.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsGeneral/Labels.tsx
- src/components/organisms/EntityList/EntityCreationModal/TestCreationModalContent.tsx
- src/components/organisms/EntityList/EntityCreationModal/TestSuiteCreationModalContent.tsx
- src/components/organisms/EntityList/EntityListFilters/LabelsFilter/LabelsFilter.tsx
> some labels and segment adjustments

- src/components/molecules/ExecutionDetails/ExecutionDetails.tsx
- src/components/molecules/ExecutionDetails/utils.ts
- src/components/organisms/EntityDetails/EntityDetailsContainer/EntityDetailsContainer.styled.tsx
- src/components/organisms/EntityDetails/EntityDetailsContainer/EntityDetailsContainer.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/ExecutionsTable/ExecutionsTable.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/ExecutionsTable/TableRow/TableRow.tsx
- src/constants/entityDetailsConfig/TestDetailsConfig.tsx
- src/constants/entityDetailsConfig/TestSuiteDetailsConfig.tsx
- src/contexts/EntityDetailsContext.tsx
- src/models/entityDetails.ts
- src/services/testSuites.ts
- src/services/tests.ts
> test suites abortion

- src/components/pages/Executors/utils.ts
- src/services/testSuites.ts
- src/services/tests.ts
- src/utils/form.tsx
> patch abortion, jmeter, monospace

- package.json
- src/redux/initialState.ts
> temporary page size update

- src/App.tsx
- src/components/pages/Sources/Sources.tsx
> added sources options

- src/App.tsx
- src/components/organisms/EntityList/EntityListFilters/EntityListFilters.tsx
- src/components/organisms/EntityList/EntityListFilters/LabelsFilter/LabelsFilter.tsx
- src/components/organisms/EntityList/EntityListFilters/StatusFilter/StatusFilter.tsx
- src/components/organisms/EntityList/EntityListFilters/TextSearchFilter/TextSearchFilter.tsx
- src/styles/globalStyles.ts
> Filters query params

- src/components/molecules/EndpointModal/EndpointModal.tsx
- src/components/molecules/ExecutionStepsList/ExecutionStepsList.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/EntityDetailsContent.tsx
- src/components/organisms/EntityList/EntityListContent/EntityListContent.tsx
- src/components/pages/Executors/ExecutorsList/AddExecutorsModal.tsx
- src/components/pages/Sources/SourcesList/AddSourceModal.tsx
- src/components/pages/Triggers/Triggers.tsx
- src/models/config.ts
- src/redux/initialState.ts
- src/redux/reducers/configSlice.ts
> select app namespace from endpoint

- src/App.tsx
> root redirest fix

- src/App.tsx
> posthog fix

- src/components/molecules/MetricsBarChart/MetricsBarChart.styled.tsx
> fix: dates on charts no wrap

- craco.config.js
- package-lock.json
- package.json
> tech: added terser plugin

- craco.config.js
- src/components/molecules/MetricsBarChart/MetricsBarChart.tsx
- src/components/molecules/MetricsBarChart/components/PAxisLine.tsx
> fixed duration bug

- src/components/organisms/EntityDetails/EntityDetailsContent/EntityDetailsContent.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/SummaryGrid/SummaryGrid.tsx
> Move chart to recent executions tab

- src/components/organisms/EntityList/EntityCreationModal/TestSuiteCreationModalContent.tsx
- src/components/wizards/AddTestWizard/utils.ts
- src/utils/form.tsx
> feat: improve k8s pattern message

- .eslintrc.js
- src/components/organisms/EntityDetails/EntityDetailsContent/SummaryGrid/SummaryGrid.styled.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/SummaryGrid/SummaryGrid.tsx
This PR resolves: https://github.com/kubeshop/testkube/issues/3046
> [#3046] Rework stats columns

- src/components/organisms/EntityDetails/EntityDetailsContent/EntityDetailsContent.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/SummaryGrid/SummaryGrid.tsx
> remove unused

- src/components/custom-antd/Checkbox/Checkbox.styled.tsx
- src/components/custom-antd/Checkbox/Checkbox.tsx
- src/components/custom-antd/Checkbox/index.ts
- src/components/custom-antd/index.ts
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/Settings.styled.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsGeneral/FailureHandling.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsGeneral/Labels.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsGeneral/NameNDescription.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsGeneral/SettingsGeneral.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTest/Source.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTest/TestType.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTests/SettingsTests.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsVariables/Variables.tsx
- src/components/pages/Sources/SourceDetails/SourceSettings/General/Authentication.tsx
- src/components/pages/Sources/SourceDetails/SourceSettings/General/NameNUrl.tsx
This PR...
- added failure handling block and ability to invert test results
- https://github.com/kubeshop/testkube/issues/2482
-
-
-
> failure handling

- src/styles/Colors.ts
> chore: update success chart color to be more green

- src/components/molecules/ConfigurationCard/ConfigurationCard.tsx
- src/utils/variables.ts
This PR...
- fixes https://github.com/kubeshop/testkube/issues/3154
- reverted default save button text
-
-
-
> removed quotes in vars

- .eslintrc.js
- src/components/organisms/EntityDetails/EntityDetailsContainer/EntityDetailsContainer.tsx
- src/contexts/EntityDetailsContext.tsx
- src/hooks/useSecureContext.ts
Resolves: https://github.com/kubeshop/testkube/issues/2962
> fix: Unable to open old executions

- src/components/organisms/EntityDetails/EntityDetailsContainer/EntityDetailsContainer.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/EntityDetailsContent.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/ExecutionsTable/ExecutionsTable.tsx
Resolves: https://github.com/kubeshop/testkube/issues/3169
> #3169 Not all executions are displayed when filtering for the timeframe 

- src/components/wizards/AddTestWizard/steps/FirstStep.tsx
- src/components/wizards/AddTestWizard/utils.ts
- src/utils/form.tsx
> fix: update form creation labels and messages

- src/App.tsx
- src/antd-theme/my-antd-theme.less
- src/components/molecules/EndpointModal/EndpointModal.styled.tsx
- src/components/molecules/EndpointModal/EndpointModal.tsx
- src/components/molecules/Notification/Notification.styled.tsx
- src/components/molecules/Notification/Notification.tsx
- src/components/organisms/Sider/Sider.tsx
- src/components/pages/GlobalSettings/General/ApiEndpoint.tsx
- src/components/pages/GlobalSettings/General/General.tsx
- src/components/pages/GlobalSettings/General/index.ts
- src/components/pages/GlobalSettings/GlobalSettings.tsx
- src/components/pages/GlobalSettings/index.ts
- src/components/pages/index.ts
- src/styles/Colors.ts
- src/styles/globalStyles.ts
- src/utils/endpoint.ts
> notification and settings refactor

- src/components/organisms/EntityDetails/EntityDetailsContent/EntityDetailsContent.tsx
- src/components/pages/GlobalSettings/General/ApiEndpoint.tsx
> some improvements

- src/components/organisms/EntityList/EntityCreationModal/TestCreationModalContent.tsx
> remove repo validation

- src/components/pages/Sources/SourceDetails/SourceSettings/General/NameNUrl.tsx
> fix: source description

- src/components/molecules/LogOutput/LogOutput.styled.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/Settings.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsExecution/PreRun.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsExecution/SettingsExecution.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsExecution/index.ts
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTest/Source.tsx
- src/components/organisms/EntityList/EntityCreationModal/TestCreationModalContent.tsx
- src/components/wizards/AddTestWizard/steps/FirstStep.tsx
- src/utils/notification.ts
> feat: Pre-run command

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- src/components/molecules/DragNDropList/DragNDropList.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTests/SettingsTests.tsx
This PR fixes the detection of changes in the Test Suite Settings form and DnD component.
- Update and set defaults of the steps in the Test Suite settings panel consistently
- Don't treat moving to the same position in DnD as a change
- https://github.com/kubeshop/testkube/issues/3353
- As per the issue above
-
> Fix detection of changes in Test Suite settings and DnD

- src/components/atoms/ExternalLink/ExternalLink.tsx
- src/components/atoms/ExternalLink/index.ts
- src/components/atoms/index.ts
- src/components/molecules/EmptyListContent/EmptyListContent.tsx
- src/components/molecules/EndpointModal/EndpointModal.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsDefinition/SettingsDefinition.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsGeneral/Timeout.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTest/Source.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTest/TestType.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTests/SettingsTests.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsVariables/Arguments.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsVariables/Variables.tsx
- src/components/pages/ErrorBoundary/ErrorBoundaryFallback.tsx
- src/components/pages/Executors/ExecutorsList/ExecutorsList.tsx
- src/components/pages/GlobalSettings/General/ApiEndpoint.tsx
- src/components/pages/Sources/SourcesList/SourcesList.tsx
- src/components/pages/Triggers/Triggers.tsx
- src/constants/entitiesConfig/TestsConfig.tsx
This PR...
- added External link component
- verify it is used in all places and behaviour it the same
-
-
-
> external link component

- src/AnalyticsProvider.tsx
Most likely new Twilio Segment's version has slightly different styles and the Docker build is not working.
https://github.com/kubeshop/testkube-dashboard/actions/runs/4730529414/jobs/8394544941#step:5:1762
```
#14 [build 7/7] RUN npm run build
#14 0.484 
#14 0.484 > testkube-dashboard@1.9.0 build
#14 0.484 > CI=false && npm run less && craco --max_old_space_size=4096 build
#14 0.484 
#14 0.792 
#14 0.792 > testkube-dashboard@1.9.0 less
#14 0.792 > lessc --js src/antd-theme/antd-customized.less src/antd-theme/antd-customized.css
#14 0.792 
#14 5.191 The following changes are being made to your tsconfig.json file:
#14 5.192   - compilerOptions.paths must not be set (aliased imports are not supported)
#14 5.192 
#14 5.244 Creating an optimized production build...
#14 86.99 Failed to …
```
> fix: TS error: ensure the context.page is available for Twilio Segment's context

- src/components/atoms/CreatableMultiSelect/CustomComponents/LabelsMultiValueLabel.tsx
- src/components/custom-antd/Typography/Text/Text.tsx
- src/components/molecules/ArtifactsList/ArtifactsList.tsx
- src/components/molecules/CLICommands/CopyCommand.tsx
- src/components/molecules/EntityGrid/EntityGridItem.tsx
- src/components/molecules/MetricsBarChart/components/BarWithTooltip.tsx
- src/components/molecules/MetricsBarChart/components/PAxisLine.tsx
- src/components/molecules/TestSuiteStepCard/TestSuiteStepCard.tsx
- src/components/molecules/Variables/ExecutionsVariablesList/ExecutionsVariablesList.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/ExecutionsTable/TableRow/TableRow.tsx
- src/components/organisms/EntityDetails/ExecutionDetailsDrawer/ExecutionDetailsDrawerHeader.tsx
- src/components/pages/Executors/ExecutorsList/ExecutorsList.tsx
- src/components/pages/Sources/SourcesList/SourcesList.tsx
- src/components/pages/Triggers/AddTriggerOption.tsx
- same as in Cloud
- Part of https://github.com/kubeshop/testkube/issues/3695
-
-
> chore: add default class name to Text

- src/App.tsx
- src/components/molecules/EmptyListContent/EmptyListContent.tsx
- src/components/molecules/EntityGrid/EntityGridItem.tsx
- src/components/molecules/ExecutionDetails/TestExecutionDetails/TestExecutionDetailsArtifacts.tsx
- src/components/molecules/LabelsSelect/LabelsSelect.tsx
- src/components/organisms/EntityDetails/EntityDetailsContainer/EntityDetailsContainer.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTests/SettingsTests.tsx
- src/components/organisms/EntityDetails/ExecutionDetailsDrawer/ExecutionDetailsDrawer.tsx
- src/components/organisms/EntityList/EntityListContent/EmptyDataWithFilters.tsx
- src/components/organisms/EntityList/EntityListContent/EntityDataLayers.tsx
- src/components/organisms/EntityList/EntityListContent/EntityListContent.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorDetails.tsx
- src/components/pages/Executors/ExecutorsList/ExecutorsList.tsx
- src/components/pages/Sources/SourceDetails/SourceDetails.tsx
- src/components/pages/Sources/SourcesList/SourcesList.tsx
- src/components/pages/Triggers/Triggers.tsx
- src/contexts/MainContext.ts
- src/services/triggers.ts
- src/utils/fetchUtils.ts
- add isClusterAvailable to make it aligned with Cloud implementation
- related to https://github.com/kubeshop/testkube-cloud-ui/pull/210
-
-
> chore: add isClusterAvailable to make it aligned with Cloud

- src/components/atoms/Dots/Dots.tsx
- src/components/custom-antd/Button/Button.styled.tsx
- src/components/custom-antd/Button/Button.tsx
- src/components/molecules/DotsDropdown/DotsDropdown.styled.tsx
- src/components/molecules/DotsDropdown/DotsDropdown.tsx
- src/components/molecules/DotsDropdown/index.ts
- src/components/molecules/index.ts
- src/components/organisms/EntityDetails/EntityDetailsContent/ExecutionsTable/TableRow/TableRow.styled.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/ExecutionsTable/TableRow/TableRow.tsx
- src/components/organisms/EntityDetails/ExecutionDetailsDrawer/ExecutionDetailsDrawerHeader.tsx
- move DotsDropdown from Cloud version (keep alignment)
-
-
> feat: move DotsDropdown from Cloud version

- src/antd-theme/my-antd-theme.less
- src/components/atoms/Asterisk/Asterisk.ts
- src/components/atoms/Asterisk/index.ts
- src/components/atoms/index.ts
- src/components/molecules/GitFormItems/Branch.tsx
- src/components/molecules/GitFormItems/Commit.tsx
- src/components/molecules/GitFormItems/FormItemLabel.tsx
- src/components/molecules/GitFormItems/Path.tsx
- src/components/molecules/GitFormItems/Repository.tsx
- src/components/molecules/GitFormItems/Revision.tsx
- src/components/molecules/GitFormItems/SecretFormItem.tsx
- src/components/molecules/GitFormItems/tooltipUtils.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTest/Source.tsx
- src/components/organisms/EntityList/EntityCreationModal/TestCreationForm/TestCreationForm.tsx
- src/components/organisms/TestConfigurationForm/Git/CreationFormFields.tsx
- src/components/organisms/TestConfigurationForm/Git/SourceEditFormFields.tsx
- src/hooks/useValidateRepository.ts
- src/utils/sources.ts
This PR...
https://github.com/kubeshop/testkube/issues/3319
- repo validation on test creation and test edit
-
-
-
> feat: Repository Validation

- src/components/organisms/EntityList/EntityListFilters/LabelsFilter/LabelsFilter.tsx
- src/components/organisms/EntityList/EntityListFilters/StatusFilter/StatusFilter.tsx
- adjust variable names in LabelsFilter
-
-
> chore: adjust variable names in LabelsFilter

- src/App.tsx
- src/components/molecules/EmptyListContent/EmptyListContent.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/EntityDetailsContent.tsx
- src/components/organisms/EntityList/EntityListContent/EntityListContent.tsx
- src/components/organisms/PageBlueprint/PageBlueprint.tsx
- src/components/organisms/Sider/Sider.tsx
- src/components/pages/ErrorBoundary/ErrorBoundaryFallback.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorDetails.tsx
- src/components/pages/Sources/SourceDetails/SourceDetails.tsx
- src/contexts/ConfigContext.ts
- src/contexts/index.ts
- create `ConfigContext` to handle Cloud/OSS differences
- related to https://github.com/kubeshop/testkube-cloud-ui/pull/220
-
-
> feat: create static config context

- src/App.tsx
- src/components/molecules/DeleteEntityModal/DeleteEntityModal.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/EntityDetailsContent.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsExecution/PreRun.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsGeneral/FailureHandling.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsGeneral/Labels.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsGeneral/NameNDescription.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsGeneral/Timeout.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsScheduling/Schedule.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTest/SettingsTest.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTests/SettingsTests.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsVariables/Arguments.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsVariables/Variables.tsx
- src/components/organisms/EntityList/EntityCreationModal/TestCreationForm/TestCreationForm.tsx
- src/components/organisms/EntityList/EntityCreationModal/TestCreationModalContent.tsx
- src/components/organisms/EntityList/EntityCreationModal/TestSuiteCreationModalContent.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/CommandAndArguments/Arguments.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/CommandAndArguments/Command.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/ContainerImage/ContainerImagePanel.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/ContainerImage/PrivateRegistry.tsx
- src/components/pages/Executors/ExecutorsList/AddExecutorsModal.tsx
- src/components/pages/Sources/SourceDetails/SourceSettings/General/Authentication.tsx
- src/components/pages/Sources/SourceDetails/SourceSettings/General/NameNUrl.tsx
- src/components/pages/Sources/SourcesList/AddSourceModal.tsx
- src/components/pages/Triggers/Triggers.tsx
- src/hooks/useAxiosInterceptors.tsx
- src/utils/notification.ts
- same as in Cloud
- Part of https://github.com/kubeshop/testkube/issues/3695
-
-
> Add automated Axios error handling

- src/antd-theme/my-antd-theme.less
- src/components/atoms/Icon/Icon.styled.tsx
- src/components/atoms/StatusIcon/StatusIcon.tsx
- src/components/atoms/TestkubeTheme/CodeTheme.ts
- src/components/custom-antd/Modal/Modal.styled.tsx
- src/components/custom-antd/Typography/Text/Text.styled.tsx
- src/components/molecules/EmptyListContent/EmptyListContent.styled.tsx
- src/components/molecules/SettingsLayout/SettingsLayout.styled.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/EntityDetailsContent.styled.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/ExecutionsTable/ExecutionsTable.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTests/SettingsTests.tsx
- src/components/organisms/EntityList/EntityListContent/EntityListContent.styled.tsx
- src/components/organisms/PageBlueprint/PageBlueprint.styled.tsx
- src/components/organisms/Sider/Sider.styled.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorDetails.styled.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/CommandAndArguments/Command.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/ContainerImage/ContainerImagePanel.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/ContainerImage/PrivateRegistry.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/General/NameNType.tsx
- src/components/pages/Executors/ExecutorsList/ExecutorsList.styled.tsx
- src/components/pages/Sources/SourceDetails/SourceDetails.styled.tsx
- src/components/pages/Sources/SourceDetails/SourceSettings/General/Authentication.tsx
- src/components/pages/Sources/SourceDetails/SourceSettings/General/NameNUrl.tsx
- src/styles/Colors.ts
- src/styles/globalStyles.ts
- It changes few small styles, so the OSS styles and code will more match the Cloud one
-
-
> fix: update styles to conform to Cloud more

- src/components/molecules/LogOutput/LogOutput.tsx
- src/services/config.ts
- src/services/executions.ts
- src/services/executors.ts
- src/services/labels.ts
- src/services/repository.ts
- src/services/sources.ts
- src/services/testSuiteExecutions.ts
- src/services/testSuites.ts
- src/services/tests.ts
- src/services/triggers.ts
- src/utils/fetchUtils.ts
- chore: unify implementation with Cloud
-
-
> Unify LogOutput implementation

- src/components/organisms/EntityDetails/EntityDetailsContainer/EntityDetailsContainer.tsx
- src/models/websocket.ts
- src/services/config.ts
- src/services/executions.ts
- src/services/executors.ts
- src/services/labels.ts
- src/services/repository.ts
- src/services/sources.ts
- src/services/testSuiteExecutions.ts
- src/services/testSuites.ts
- src/services/tests.ts
- src/services/triggers.ts
- src/utils/fetchUtils.ts
- chore: unify implementation with Cloud
- feat: allow Test Suites update based on WebSocket
-
-
> Unify EntityDetailsContainer

- src/components/atoms/Loader/Loader.styled.tsx
- src/components/atoms/Loader/Loader.tsx
- src/components/atoms/Loader/index.ts
- src/components/atoms/index.ts
- src/components/molecules/ArtifactsList/ArtifactsList.styled.tsx
- src/components/molecules/ArtifactsList/ArtifactsList.tsx
- src/components/molecules/ArtifactsList/ArtifactsListItem.styled.tsx
- src/components/molecules/ArtifactsList/ArtifactsListItem.tsx
- src/components/molecules/ExecutionDetails/TestExecutionDetails/TestExecutionDetailsArtifacts.tsx
- src/components/molecules/ExecutionDetails/TestExecutionDetails/TestExecutionDetailsTabs.tsx
- src/services/artifacts.ts
- src/services/config.ts
- src/services/executions.ts
- src/services/executors.ts
- src/services/labels.ts
- src/services/repository.ts
- src/services/sources.ts
- src/services/testSuiteExecutions.ts
- src/services/testSuites.ts
- src/services/tests.ts
- src/services/triggers.ts
- src/utils/fetchUtils.ts
- Allow both returned blob and signed URL from the API for downloading artifact
- Unify the code with Cloud
- Related to https://github.com/kubeshop/testkube-cloud-ui/pull/233
-
-
> chore: align artifacts implementation with Cloud

- src/components/atoms/Icon/Icon.tsx
- src/components/custom-antd/Modal/Modal.tsx
- src/components/molecules/CLICommands/CLICommands.tsx
- src/components/molecules/DragNDropList/DragNDropList.tsx
- src/components/molecules/TestSuiteStepCard/TestSuiteStepCard.styled.tsx
- src/components/molecules/TestSuiteStepCard/TestSuiteStepCard.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsDefinition/SettingsDefinition.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTests/SettingsTests.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/ExecutorDefinition/ExecutorDefinition.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/General/Delete.tsx
- src/components/pages/Executors/ExecutorsList/ExecutorsList.tsx
- src/components/pages/NotFound/NotFound.tsx
- src/components/pages/Sources/SourceDetails/SourceSettings/Definition/SourceSettingsDefinition.tsx
- src/components/pages/Sources/SourceDetails/SourceSettings/General/Delete.tsx
- src/components/pages/Triggers/Triggers.tsx
- src/utils/externalLinks.ts
- src/utils/notification.ts
- add missing `<Form>` wrappers
- move and adjust some improvements from Cloud to OSS
-
-
> feat: various alignments with Cloud

- src/AnalyticsProvider.tsx
- src/AppRoot.tsx
- src/components/molecules/EntityGrid/EntityGrid.tsx
- src/components/molecules/EntityGrid/EntityGridItem.tsx
- src/components/molecules/EntityGrid/EntityGridItemPure.tsx
- src/components/molecules/MetricsBarChart/MetricsBarChart.styled.tsx
- src/components/molecules/MetricsBarChart/components/BarWithTooltip.tsx
- src/components/molecules/MetricsBarChart/components/BarWithTooltipPure.tsx
- src/components/organisms/EntityDetails/EntityDetailsContainer/EntityDetailsContainer.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/ExecutionsTable/ExecutionsTable.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/ExecutionsTable/TableRow/TableRow.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/ExecutionsTable/TableRow/TableRowPure.tsx
- src/components/organisms/EntityList/EntityListContent/EntityListContent.tsx
- src/services/config.ts
- src/services/executors.ts
- src/services/labels.ts
- src/services/sources.ts
- src/services/testSuiteExecutions.ts
- src/services/testSuites.ts
- src/services/tests.ts
- src/services/triggers.ts
- src/utils/fetchUtils.ts
This PR aims into drastically improve the performance (and CPU use) of the application. CPU usage is few times lower, and the interface is much more smooth.
- When polling data and there is no difference, keep the previous identity for strict equality
- Cut metrics and executions list to last 1000 items
- Add [**dumb components**](https://medium.com/@thejasonfile/dumb-components-and-smart-components-e7b33a698d43) for components that are responsible for most performance problems - `EntityGridItem`, `BarWithTooltip`, and `TableRow`
- Minor adjustments
- https://github.com/kubeshop/testkube/issues/3744
- Start (even better if production build) and go through the app
-
> Optimize UI performance

- src/AnalyticsProvider.tsx
- src/AppRoot.tsx
- src/contexts/AnalyticsContext.ts
This PR aligns the attributes of the AnalyticsContext with cloud, by adding support for feature flags also to OSS.
-
-
-
-
> feat: align AnalyticsContext with cloud

- .github/workflows/docker-build-beta-tag.yml
This PR...
**Test commit** 
-
-
-
-
> ci: test ci to develop

- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTests/SettingsTests.tsx
> fix: get test-suite list after creation

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- .github/workflows/triage.yml
- After changing the release process, we're making PRs to `develop` branch. It should have all the integrated checks too.
-
-
-
> fix: run GitHub workflows for develop PRs too

- .github/workflows/docker-build-tag.yml
This PR...
Add check for release branch.
-
-
-
-
> ci: update ci for tag creation

- .github/workflows/docker-build-release.yml
> fix: docker workflows (hotfix)

- .github/workflows/docker-build-release.yml
> fix: adjust build release workflow

- src/antd-theme/my-antd-theme.less
- src/components/atoms/Icon/Icon.tsx
- src/components/atoms/Icon/icons.tsx
- src/components/atoms/Icon/types.ts
- src/components/atoms/StatusIcon/StatusIcon.tsx
- src/components/molecules/DotsDropdown/DotsDropdown.styled.tsx
- src/components/molecules/DotsDropdown/DotsDropdown.tsx
- src/components/molecules/EntityGrid/EntityGrid.styled.tsx
- src/components/molecules/EntityGrid/EntityGridItem.tsx
- src/components/molecules/EntityGrid/EntityGridItemPure.tsx
- src/components/molecules/MetricsBarChart/components/Chart.tsx
- src/components/organisms/EntityDetails/EntityDetailsContainer/EntityDetailsContainer.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/EntityDetailsContent.tsx
- src/components/organisms/EntityList/EntityListContainer/EntityListContainer.tsx
- src/constants/entitiesConfig/TestSuitesConfig.tsx
- src/constants/entitiesConfig/TestsConfig.tsx
- src/constants/entityDetailsConfig/TestDetailsConfig.tsx
- src/constants/entityDetailsConfig/TestSuiteDetailsConfig.tsx
- src/contexts/EntityDetailsContext.tsx
- src/models/entity.ts
- src/models/entityDetails.ts
- src/services/testSuites.ts
- src/services/tests.ts
- src/styles/Colors.ts
- src/styles/globalStyles.ts
This PR...
- added multiple abortion on list and details pages
- added `aborting` status
- improved `DotsDropdown` copmponent
-
-
-
> Multiple test/test-suite execution abortion

- src/components/atoms/CommandInput/CommandInput.tsx
- src/components/atoms/CommandInput/index.ts
- src/components/atoms/index.ts
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsExecution/PreRun.tsx
- src/components/pages/Executors/ExecutorDetails/ExecutorSettings/CommandAndArguments/Command.tsx
This PR...
- added CommandInput atom
- used in executors command and prerun script for tests
- https://github.com/kubeshop/testkube/issues/3529
-
-
> Consistent cmd input

- src/components/molecules/EntityGrid/EntityGridItemPure.tsx
This PR fixes the `EntityGridItemPure` component
> fix: deleted a redundant row from entity grid item

- src/utils/formatDate.spec.ts
- src/utils/formatDate.ts
- fix calculating duration
- https://github.com/kubeshop/testkube/issues/3743
-
-
> fix: round test duration correctly

- src/components/custom-antd/Skeleton/Skeleton.styled.tsx
- sometimes the skeleton is moving outside of its place, glitching like the whole container is moving
- applying background, so it's not visible
-
-
-
> fix: glitching skeleton animation

- src/components/molecules/GitFormItems/SecretFormItem.tsx
- src/components/pages/Sources/SourceDetails/SourceDetails.styled.tsx
- src/components/pages/Sources/SourceDetails/SourceSettings/General/Authentication.tsx
- src/components/pages/Sources/SourceDetails/SourceSettings/General/NameNUrl.tsx
- src/components/pages/Sources/SourcesList/AddSourceModal.tsx
- src/models/sources.ts
- src/services/sources.ts
- Fix updating the token/username (use `SecretFormItem`, same as for tests, and adjust the payloads)
- Fix creating a test source with token/username (adjust the payloads)
- Fix displaying Test Source's Git URI (it was not refreshing)
- https://github.com/kubeshop/testkube/issues/3810
-
-
> fix: use Git tokens and Git usernames correctly for the Test Sources

- src/components/organisms/EntityDetails/EntityDetailsContent/EntityDetailsContent.tsx
- src/components/organisms/Sider/Sider.tsx
- src/components/organisms/Sider/SiderLink.tsx
This PR...
- `findDOMNode` errors
- missing `key` error
-
-
-
> fix: some console errors

- src/components/pages/GlobalSettings/General/ApiEndpoint.tsx
- src/components/pages/GlobalSettings/General/ConnectCloud.tsx
- src/components/pages/GlobalSettings/General/General.tsx
> feat: connect to testkube cloud

- .github/workflows/docker-build-release.yml
This PR...
Fix creation of release branch.
-
-
-
-
> ci: fix naming

- .github/workflows/docker-build-release.yml
This PR...
Fix naming if release branch.
-
-
-
-
> fix naming of release branch

- src/styles/globalStyles.ts
Prev: <img width="1792" alt="image" src="https://github.com/kubeshop/testkube-cloud-ui/assets/25991946/ec41b0c8-0d07-4345-acab-e983ff1a0782">
Now: <img width="1792" alt="image" src="https://github.com/kubeshop/testkube-cloud-ui/assets/25991946/b7718ef0-7544-4965-97a0-9fcf199276b6">
> fix: fixed home page UI

- Dockerfile
- nginx/nginx.conf
-
- https://github.com/kubeshop/testkube/issues/3846
-
-
> Hotfix v1.11.3 (IPv6 support)

- src/components/organisms/Sider/Sider.tsx
> Fix sider links

- src/utils/externalLinks.ts
> feat: add contact Us external link

- .github/workflows/docker-build-develop.yml
- .github/workflows/docker-build-tag.yml
This PR adds GH acton to upload README file to the Docker registry: https://hub.docker.com/repository/docker/kubeshop/testkube-dashboard/general
-
-
-
-
> ci: add docker registry description

- .prettierrc.js
> Allow using Prettier from different Working Directory

- .github/workflows/docker-build-release.yml
Added workflow dispatch for release to be able to trigger it manually the first time branch is created.
https://github.com/orgs/community/discussions/54860
-
-
-
-
> ci: add workflow dispatch

- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTests/SettingsTests.tsx
- load test suite steps properly
- kubeshop/testkube#3940
- For example, connect to `integration.testkube.io` and go to `/test-suites/executions/jacek-ts`
-
> fix: show existing Test Suite steps

- src/components/pages/Executors/ExecutorDetails/ExecutorDetails.tsx
- src/redux/reducers/executorsSlice.ts
- fix fetching data for newly created executor
- fix fetching on URL change
- kubeshop/testkube#3952
-
-
> fix: load executor details when opening the page

- src/store/utils.tsx
- allow providing initial state for the Zustand store
- it allows to override static values (not a function)
-
-
> feat: allow providing initial state for stores

- src/components/molecules/MessagePanel/MessagePanel.tsx
- src/components/organisms/Sider/Sider.tsx
- avoid some errors in console
-
-
-
> fix: some errors from console

- src/utils/sources.ts
- https://github.com/kubeshop/testkube/issues/4009
-
-
-
> v1.12.2 hotfix

- src/components/custom-antd/Button/Button.styled.tsx
- src/styles/Colors.ts
Merge with [this](https://github.com/kubeshop/testkube-cloud-ui/pull/346)
> feat: updated btn

- test/dashboard-e2e/api/api-helpers.js
- test/dashboard-e2e/pages/MainPage.ts
- test/dashboard-e2e/tests/create-test.spec.ts
- test/dashboard-e2e/tests/run-test.spec.ts
Making OSS E2E tests cloud-aware - allowing to run them for Cloud
```
Running 40 tests using 8 workers
34 skipped
6 passed (9.6s)
``` (Cloud dev)
> OSS E2E tests - cloud awareness

- src/components/molecules/ArtifactsList/ArtifactsList.tsx
- src/components/molecules/ArtifactsList/ArtifactsListItem.styled.tsx
- src/components/molecules/ExecutionDetails/TestExecutionDetails/TestExecutionDetailsArtifacts.tsx
- src/components/molecules/ExecutionDetails/TestExecutionDetails/TestExecutionDetailsTabs.tsx
- src/services/artifacts.ts
This PR...
- download artifacts archive
-
-
-
> feat: Download all artifacts

- src/components/organisms/TestConfigurationForm/StringContentFields/StringContentFields.tsx
- src/components/pages/Tests/TestsList/TestCreationModalContent/TestCreationForm.tsx
This PR...
https://github.com/kubeshop/testkube/issues/3991
-
-
-
-
> Improve placeholders for k6 + curl test creation

- .github/workflows/docker-build-release.yml
- .github/workflows/docker-build-tag.yml
This PR removes creation of release branch in helm-charts repo to simplify release flow. 
-
-
-
-
> ci: remove release branch creation in helm-charts repo

- src/components/molecules/LogOutput/FullscreenLogOutput/FullScreenLogOutput.tsx
- src/components/molecules/LogOutput/FullscreenLogOutput/FullscreenLogOutput.styled.tsx
> fix: fullscreen log output transition

- src/components/molecules/LogOutput/LogOutput.tsx
> tech: add logs test id

- src/components/molecules/DragNDropList/DragNDropList.tsx
- src/components/molecules/ExecutionDetails/TestSuiteExecutionDetails/TestSuiteExecutionDetailsTabs.tsx
- src/components/molecules/ExecutionStepsList/ExecutionStepsList.styled.tsx
- src/components/molecules/ExecutionStepsList/ExecutionStepsList.tsx
- src/components/molecules/TestSuiteStepCard/TestSuiteStepCard.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTests/SettingsTests.tsx
- src/models/testSuite.ts
- src/models/testSuiteExecution.ts
This PR...
- changed dashboard test suite features so it match with Test Suites V3
https://github.com/kubeshop/testkube/blob/develop/api/v1/testkube.yaml#L3057
-
-
-
> Test suite v3 format support

- public/index.html
- update meta description for the Dashboard
-
-
-
> fix: update meta description for the Dashboard

- jest.config.js
- package.json
- Add support for [**Wallaby.js**](https://wallabyjs.com/), which greatly improves the performance of writing unit tests
- the response is immediate and in IDE (including debugging and logs),
- you may easily discover which parts are completely not covered (via gray/yellow blocks next to line numbers),
- Install [**Wallaby.js**](https://wallabyjs.com/)
- Open this branch
- Play around
Don't worry about the delays in the video - normally it works immediately, I've got some performance issues with my computer though, especially when conferencing or recording.
https://github.com/kubeshop/testkube-dashboard/assets/3843526/56531ce1-bdfb-4e34-a356-82cbc08641f5
> feat: add Wallaby.js support

- test/dashboard-e2e/config.ts
- test/dashboard-e2e/pages/MainPage.ts
- test/dashboard-e2e/playwright.config.ts
- test/dashboard-e2e/tests/create-test.spec.ts
- test/dashboard-e2e/tests/executors.spec.ts
- test/dashboard-e2e/tests/run-test.spec.ts
- test/dashboard-e2e/tests/testsuite.spec.ts
- extract Playwright configuration variables to separate typed file
-
-
-
> chore/fix: extract Playwright configuration variables to separate typed file

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- package.json
- test/dashboard-e2e/tests/test-sources.spec.ts
- check TypeScript types on PR
- fix E2E types
-
-
-
> feat: check TypeScript types on PR / fix e2e types

- src/telemetry/TelemetryService.ts
- fix: send telemetry data even when not debugging telemetry
- kubeshop/testkube#4118
-
-
> fix: send telemetry data even when not debugging telemetry

- src/components/organisms/PageBlueprint/PageBlueprint.styled.tsx
- ensure that the page will not be wider than full screen
- kubeshop/testkube#4165
-
-
> fix: ensure that the page will not be wider than full screen

- src/antd-theme/my-antd-theme.less
- src/components/molecules/ConfigurationCard/ConfigurationCard.styled.tsx
- src/components/molecules/ConfigurationCard/ConfigurationCard.tsx
- src/styles/globalStyles.ts
> feat: switch styling & configuration card enhancement

- src/AppRoot.tsx
- src/components/atoms/Tag/Tag.styled.tsx
- src/components/atoms/Tag/Tag.tsx
- src/components/atoms/Tag/index.ts
- src/components/atoms/index.ts
- src/components/organisms/EntityList/EntityListContent/EntityListContent.tsx
- src/components/organisms/PageBlueprint/PageBlueprint.styled.tsx
- src/components/organisms/PageBlueprint/PageHeader.tsx
- src/components/pages/TestSuites/TestSuitesList/TestSuitesList.tsx
- src/models/entity.ts
- src/plugins/pluginHooks.ts
- src/styles/Colors.ts
This PR...
- creates new plugin slot for TestSuite title icon
- creates new plugin hook to fetch single component for slot
- creates new Tag component
-
-
-
-
> feat: add test suite title plugin slot

- src/services/apiEndpoint.ts
> fix: agent info url and token

- src/components/atoms/CopyButton/CopyButton.styled.tsx
- src/components/molecules/ExecutionDetails/TestExecutionDetails/TestExecutionDetailsTabs.tsx
- src/components/molecules/LogOutput/LogOutput.styled.tsx
- src/components/molecules/LogOutput/LogOutput.tsx
- src/components/molecules/MessagePanel/MessagePanel.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsDefinition/utils.ts
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTests/Modals/DelayModal.tsx
- src/components/organisms/EntityDetails/EntityDetailsContent/Settings/SettingsTests/TestSuiteStepsFlow.tsx
- src/components/organisms/EntityDetails/ExecutionDetailsDrawer/ExecutionDetailsDrawer.styled.tsx
- src/components/organisms/EntityDetails/ExecutionDetailsDrawer/ExecutionDetailsDrawer.tsx
- src/components/pages/Tests/Tests.tsx
- src/constants/config.ts
- src/plugins/definitions/ai-insights.tsx
- src/plugins/types.ts
> feat: ai banner slot

- src/components/molecules/LogOutput/LogOutput.tsx
- src/constants/config.ts
- src/plugins/definitions/ai-insights.tsx
> fix: AI banner visibility

- src/contexts/MainContext.ts
> feat: enhance main context

- test/dashboard-e2e/pages/CreateTestPage.ts
- scroll the virtual list, until the expected option will be rendered
- kubeshop/testkube#4199
-
-
> fix: E2E: scroll virtual list in Test Sources until the expected one is there

- src/env.ts
- delete unused `segmentKey`/`posthogKey`
-
-
-
> chore: delete unused segmentKey/posthogKey

- src/components/atoms/SplitLabelText/SplitLabelText.styled.ts
- src/components/atoms/SplitLabelText/SplitLabelText.tsx
- fix positioning of labels
- kubeshop/testkube#4278
-
-
> fix: positioning of labels

- src/components/organisms/EntityDetails/EntityDetailsHeader.tsx
- src/components/pages/TestSuites/TestSuiteDetails/TestSuiteDetailsContent.tsx
- src/components/pages/Tests/TestDetails/TestDetailsContent.tsx
> feat: edit test/test-suites button

- src/AppRoot.tsx
- src/plugins/definitions/ai-insights.tsx
- enable AI banner again
-
-
-
> chore: enable AI banner again

- src/App.tsx
- src/components/molecules/MessagePanel/MessagePanel.tsx
- src/plugins/definitions/ai-insights.tsx
> tech: unify MessagePanel

- src/components/molecules/RunningContext/ContextDisplay.tsx
- src/components/molecules/RunningContext/RunningContext.tsx
-
- kubeshop/testkube#4024
- kubeshop/testkube#4294
-
-
> fix: improves for the test/test suite context

- src/components/organisms/EntityDetails/EntityDetails.styled.tsx
> fix: Adjust details wrapper

- src/App.tsx
- src/components/molecules/MessagePanel/MessagePanel.styled.tsx
- src/components/molecules/MessagePanel/MessagePanel.tsx
- src/plugins/definitions/ai-insights.tsx
> chore: Change default position to inline

- src/components/pages/Tests/TestDetails/TestSettings/SettingsVariables/Arguments.tsx
> fix: change test arguments

- src/components/pages/Webhooks/WebhookCreationModal/FirstStep.tsx
- src/components/pages/Webhooks/WebhookCreationModal/SecondStep.tsx
- src/components/pages/Webhooks/WebhookCreationModal/WebhookCreationModal.tsx
- src/components/pages/Webhooks/WebhookDetails/ConditionTab/Condition.tsx
> fix: webhook creation modal bugs

- src/components/pages/Tests/TestDetails/TestSettings/SettingsGeneral/SettingsGeneral.tsx
> feat: delete tests plugin extension

- src/components/pages/TestSuites/TestSuitesList/TestSuiteCreationModalContent/TestSuiteCreationModalContent.tsx
> fix: create new test suites

- src/components/pages/TestSuites/TestSuiteDetails/TestSuiteSettings/SettingsGeneral/SettingsGeneral.tsx
> feat: add test suite delete slot

- src/components/atoms/CreatableMultiSelect/CreatableMultiSelect.tsx
- src/components/molecules/LabelsSelect/LabelsSelect.tsx
- src/components/pages/Tests/TestsList/TestCreationModalContent/TestCreationForm.tsx
> fix: add labels select id

- .github/workflows/pr_checks.yml
- src/components/atoms/CreatableMultiSelect/CreatableMultiSelect.styled.tsx
- src/components/atoms/CreatableMultiSelect/CreatableMultiSelect.tsx
- src/components/atoms/CreatableMultiSelect/CustomComponents/LabelsOption.tsx
- src/components/atoms/SplitLabelText/SplitLabelText.tsx
- src/components/molecules/LabelsSelect/LabelsSelect.tsx
- src/components/molecules/LabelsSelect/utils.ts
| Commit | Description | PR |
|-|-|-|
|[**`69d176c3`**](https://github.com/kubeshop/testkube-dashboard/commit/69d176c3)| fix: handle lack of labels, avoid duplicates in the labels combo-box|([#881](https://github.com/kubeshop/testkube-dashboard/pull/881))|
|[**`7df1a7f3`**](https://github.com/kubeshop/testkube-dashboard/commit/7df1a7f3)| dev uri updated|([#880](https://github.com/kubeshop/testkube-dashboard/pull/880))|
> Release v1.14.2

- src/components/pages/Executors/ExecutorsList/AddExecutorsModal.tsx
- src/components/pages/Sources/SourcesList/AddSourceModal.tsx
- src/components/pages/TestSuites/TestSuitesList/TestSuiteCreationModalContent/TestSuiteCreationModalContent.tsx
- src/components/pages/Tests/TestsList/TestCreationModalContent/TestCreationForm.tsx
- src/components/pages/Webhooks/WebhookCreationModal/WebhookCreationModal.tsx
This PR...
- disbale autoComplete for form names
-
-
-
> fix: disable auto complete input name

- src/AppRoot.tsx
> fix: reset RTK cache correctly

- src/components/pages/TestSuites/TestSuiteDetails/TestSuiteSettings/SettingsTests/Nodes/StepNode.tsx
> feat: parallel test suite add test link

- src/components/molecules/ConfigurationCard/ConfigurationCard.tsx
- src/components/molecules/SettingsLeftNavigation/SettingsLeftNavigation.tsx
- src/components/organisms/TriggersFormItems/ActionFormItems.tsx
- src/components/organisms/TriggersFormItems/ConditionFormItems.tsx
- src/components/organisms/TriggersFormItems/TriggerSelectorSwitcher/TriggerSelectorSwitcher.tsx
- src/components/pages/Triggers/TriggerDetails/TriggerDetails.tsx
- src/components/pages/Triggers/TriggersList/AddTriggerModal/AddTriggerModal.tsx
- src/components/pages/Triggers/TriggersList/AddTriggerModal/ModalFirstStep.tsx
- src/components/pages/Triggers/TriggersList/AddTriggerModal/ModalSecondStep.tsx
- src/components/pages/Triggers/TriggersList/TriggerCard.tsx
- src/components/pages/Triggers/TriggersList/TriggersList.tsx
- src/components/pages/Webhooks/WebhookCreationModal/FirstStep.tsx
- src/components/pages/Webhooks/WebhookCreationModal/SecondStep.tsx
- src/components/pages/Webhooks/WebhookCreationModal/WebhookCreationModal.tsx
- src/components/pages/Webhooks/WebhookDetails/WebhookDetails.tsx
- src/components/pages/Webhooks/WebhooksList/WebhookCard.tsx
- src/components/pages/Webhooks/WebhooksList/WebhooksList.tsx
- src/modal/context.tsx
- Add `data-test` attributes for Triggers & Webhooks
-
-
-
> Add data-test attributes for Triggers & Webhooks

- .dockerignore
- .eslintrc.js
- .gitignore
- Dockerfile
- Makefile
- jest.config.js
- nginx/nginx.conf
- package-lock.json
- packages/web/package.json
- packages/web/scripts/env.sh
- packages/web/src/store/clusterDetails.ts
- packages/web/src/store/entityDetails.ts
- packages/web/src/store/executionDetails.ts
- packages/web/src/store/executors.ts
- packages/web/src/store/logOutput.ts
- packages/web/src/store/sources.ts
- packages/web/src/store/testSuites.ts
- packages/web/src/store/tests.ts
- packages/web/src/store/triggers.ts
- packages/web/src/store/webhooks.ts
- Unify Docker image with Cloud
- Adjust test configuration
- Adjust ignored files
- Delete false-positive ESLint rules
- Adjust store utils import a little
- It improves a little cross-package resolution
-
-
-
> fix: mono-repository adjustments, fixing Docker image to support read-only file system with volumes

- packages/web/src/components/molecules/AiInsightsTab/AiInsightsTab.spec.tsx
- packages/web/src/components/molecules/AiInsightsTab/AiInsightsTab.tsx
- packages/web/src/components/molecules/ArtifactsList/ArtifactsListItem.spec.tsx
- packages/web/src/components/molecules/ArtifactsList/ArtifactsListItem.tsx
- packages/web/src/components/molecules/CommonSettings/Delete.spec.tsx
- packages/web/src/components/molecules/CommonSettings/Delete.tsx
- packages/web/src/components/molecules/ConfigurationCard/ConfigurationCard.tsx
- packages/web/src/components/molecules/DeleteEntityModal/DeleteEntityModal.tsx
- packages/web/src/components/organisms/CardForm/CardForm.tsx
- packages/web/src/components/pages/GlobalSettings/General/ConnectCloud.tsx
- packages/web/src/components/pages/GlobalSettings/General/YourInstallation/YourInstallation.tsx
- packages/web/src/utils/mocks.ts
> tech: improve unit test coverage

- packages/web/src/components/molecules/EntityGrid/EntityGridItemPure.tsx
- packages/web/src/components/molecules/RunningContext/ContextDisplay.tsx
- packages/web/src/components/organisms/EntityDetails/EntityDetailsHeader.tsx
- packages/web/src/components/pages/TestSuites/TestSuiteDetails/TestSuiteDetailsContent.tsx
- packages/web/src/components/pages/TestSuites/TestSuiteDetails/TestSuiteSettings/SettingsDefinition/SettingsDefinition.tsx
- packages/web/src/components/pages/TestSuites/TestSuiteDetails/TestSuiteSettings/SettingsGeneral/SettingsGeneral.tsx
- packages/web/src/components/pages/TestSuites/TestSuiteDetails/TestSuiteSettings/SettingsTests/Modals/TestModal.tsx
- packages/web/src/components/pages/TestSuites/TestSuiteDetails/TestSuiteSettings/SettingsTests/SettingsTests.tsx
- packages/web/src/components/pages/TestSuites/TestSuiteDetails/TestSuiteSettings/SettingsVariables/SettingsVariables.tsx
- packages/web/src/components/pages/TestSuites/TestSuitesList/TestSuiteCard.tsx
- packages/web/src/components/pages/TestSuites/TestSuitesList/TestSuitesList.tsx
- packages/web/src/components/pages/Tests/TestDetails/TestDetailsContent.tsx
- packages/web/src/components/pages/Tests/TestDetails/TestSettings/SettingsGeneral/SettingsGeneral.tsx
- packages/web/src/components/pages/Tests/TestDetails/TestSettings/SettingsVariables/SettingsVariables.tsx
- packages/web/src/components/pages/Tests/TestsList/TestCard.tsx
- packages/web/src/components/pages/Tests/TestsList/TestsList.tsx
- packages/web/src/models/testSuite.ts
- packages/web/src/utils/fetchUtils.ts
> feat: offline test suites

- packages/web/src/components/pages/TestSuites/TestSuitesList/EmptyTestSuites.tsx
> fix: messaging for empty test suite list

- packages/web/src/feature-flags/hooks.spec.tsx
- packages/web/src/hooks/useClusterVersionMatch.spec.tsx
- packages/web/src/hooks/useCopyToClipboard.spec.ts
- packages/web/src/hooks/useIsRunning.spec.ts
- packages/web/src/hooks/useLastCallback.test.ts
- packages/web/src/hooks/useLoadingIndicator.spec.ts
- packages/web/src/hooks/useSystemAccess.spec.tsx
- packages/web/src/utils/mocks.ts
> tech: improve unit test coverage of hooks

- packages/web/src/components/molecules/EmptyListContent/EmptyListContent.tsx
- packages/web/src/components/organisms/ExecutionsTable/EmptyExecutionsListContent/EmptyExecutionsListContent.tsx
> fix: TKC-779

- packages/web/src/components/pages/Webhooks/WebhookDetails/ActionTab/CustomPayload.tsx
- packages/web/src/components/pages/Webhooks/WebhookDetails/ActionTab/Headers.tsx
- packages/web/src/components/pages/Webhooks/WebhookDetails/ConditionTab/Condition.tsx
> fix: webhooks help links

- packages/web/src/components/organisms/EntityDetails/EntityDetailsLayer.tsx
- packages/web/src/components/pages/TestSuites/TestSuitesList/EmptyTestSuites.tsx
- packages/web/src/components/pages/Tests/TestsList/EmptyTests.tsx
> fix: offline filter change fetching

- packages/web/src/components/pages/TestSuites/TestSuiteDetails/TestSuiteSettings/SettingsTests/TestSuiteStepsFlow.tsx
> fix: readonly parallel tests

- packages/web/src/plugins/promo-banners/config.ts
- packages/web/src/plugins/promo-banners/hooks/useDisplayedPromoBanner.spec.tsx
- packages/web/src/plugins/promo-banners/hooks/useDisplayedPromoBanner.ts
- add option to make banner not rotating
-
-
-
> feat: add option to make banner not rotating

- packages/web/src/components/pages/Tests/TestDetails/TestSettings/SettingsVariables/Arguments.tsx
> fix: quoted argument

- packages/web/src/components/pages/Tests/TestDetails/TestSettings/SettingsVariables/Arguments.tsx
- detect dirty state correctly for the arguments
- after saving the arguments, the form stayed dirty - the user had confirmation message on navigation
-
-
> fix: detect dirty state correctly for the arguments

- packages/web/src/plugins/tests-and-test-suites/plugin.tsx
> feat: add new test details tab route

- packages/web/src/components/custom-antd/Button/Button.styled.tsx
- packages/web/src/components/organisms/PageBlueprint/PageBlueprint.styled.tsx
- Add `$fullWidth` prop to custom button
- Vertical align page title items
-
-
-
> fix: downgrade bugs improvements

- packages/web/src/components/pages/Executors/ExecutorsList/EmptyCustomExecutors.tsx
- packages/web/src/components/pages/Executors/ExecutorsList/ExecutorsList.tsx
- packages/web/src/components/pages/Sources/SourcesList/EmptySources.tsx
- packages/web/src/components/pages/Sources/SourcesList/SourcesList.tsx
- packages/web/src/components/pages/TestSuites/TestSuitesList/TestSuitesList.tsx
- packages/web/src/components/pages/Tests/TestsList/TestsList.tsx
- packages/web/src/components/pages/Triggers/TriggersList/EmptyTriggers.tsx
- packages/web/src/components/pages/Triggers/TriggersList/TriggersList.tsx
- packages/web/src/components/pages/Webhooks/WebhooksList/EmptyWebhooks.tsx
- packages/web/src/components/pages/Webhooks/WebhooksList/WebhooksList.tsx
This PR...
- remove infinite loading state for entities when agent is down on free plan
- fix crashing webhooks page  when agent is down on free plan 
-
-
-
> feat: free org empty entities

- packages/web/src/components/molecules/ConfigurationCard/ConfigurationCard.tsx
- packages/web/src/components/organisms/CardForm/CardForm.tsx
- Add `confirmDisabled` for configuration card
-
-
-
> feat: confirm disabled for configuration card

- packages/web/src/styles/Colors.ts
> chore: add color to palette

- packages/web/src/components/atoms/InstallationInfoItem/InstallationInfoItem.styled.tsx
- packages/web/src/components/atoms/InstallationInfoItem/InstallationInfoItem.tsx
- packages/web/src/components/atoms/InstallationInfoItem/index.ts
- packages/web/src/components/atoms/index.ts
- packages/web/src/components/pages/GlobalSettings/General/YourInstallation/YourInstallation.styled.tsx
- packages/web/src/components/pages/GlobalSettings/General/YourInstallation/YourInstallation.tsx
- Create `InstallationInfoItem` atom component
-
-
-
> feat: create InstallationInfoItem atom component

- packages/web/src/models/execution.ts
> refactor: add pending status

- packages/web/src/components/organisms/EntityView/EntityView.tsx
- packages/web/src/components/pages/TestSuites/TestSuitesList/TestSuitesList.tsx
- packages/web/src/components/pages/Tests/TestsList/TestsList.tsx
- packages/web/src/models/entity.ts
> refactor: remove isListLoading prop

- packages/web/src/components/molecules/Console/Console.tsx
- packages/web/src/components/molecules/Console/ConsoleLines.tsx
- packages/web/src/components/molecules/LogOutput/LogOutput.tsx
- packages/web/src/components/molecules/LogOutput/LogOutputPure.tsx
- packages/web/src/styles/Colors.ts
- If `L` search param is found, scroll to the line and select log line
> feat: on log click

- packages/web/src/components/organisms/EntityDetails/EntityDetailsLayer.tsx
- packages/web/src/components/organisms/ExecutionsTable/ExecutionsFilters/ExecutionsFilters.styled.tsx
- packages/web/src/components/organisms/ExecutionsTable/ExecutionsFilters/ExecutionsFilters.tsx
- packages/web/src/components/organisms/ExecutionsTable/ExecutionsFilters/ExecutionsStatusFilter.tsx
- packages/web/src/components/organisms/ExecutionsTable/ExecutionsFilters/index.ts
- packages/web/src/components/organisms/ExecutionsTable/ExecutionsTable.tsx
- packages/web/src/models/execution.ts
- packages/web/src/services/testSuites.ts
- packages/web/src/services/tests.ts
- packages/web/src/store/entityDetails.ts
- Adds search/status filters for executions
> feat: add search + status executions filters

- packages/web/src/utils/externalLinks.ts
> chore: add circleci url constant

- packages/web/src/components/molecules/HelpCard/HelpCard.styled.tsx
- packages/web/src/components/molecules/HelpCard/HelpCard.tsx
> feat: add prefix & suffix to HelpCard

- packages/web/src/models/execution.ts
- packages/web/src/services/testSuites.ts
- packages/web/src/services/tests.ts
> feat: enhance executions model

- packages/web/src/components/molecules/ArtifactsList/ArtifactsList.tsx
- packages/web/src/services/artifacts.ts
- Download all button for artifacts
- Go to the artifacts tab
- Try downloading all artifacts when more than 1
> fix: download artifacts archive

- packages/web/src/components/organisms/ExecutionsTable/ExecutionsFilters/ExecutionsFilters.tsx
- Don't disable search filter on loading
-
-
> fix: executions search filter

- packages/web/src/components/organisms/TestConfigurationForm/StringContentFields/StringContentFields.tsx
- packages/web/src/utils/sources.ts
> feat: optional string source

- packages/web/src/components/molecules/ArtifactsList/ArtifactsList.tsx
> fix: missing artifacts

- packages/web/src/plugins/promo-banners/config.ts
> feat: enhance promo banner

- packages/web/src/components/molecules/ArtifactsList/ArtifactsList.styled.tsx
- packages/web/src/components/molecules/ArtifactsList/ArtifactsList.tsx
- packages/web/src/components/molecules/ArtifactsList/ArtifactsListItem.spec.tsx
- packages/web/src/components/organisms/EntityView/EntityView.tsx
- packages/web/src/components/pages/Tests/TestDetails/TestExecution/TestExecutionArtifacts.tsx
- packages/web/src/models/artifact.ts
- packages/web/src/plugins/tests-and-test-suites/plugin.tsx
- Add plugin slot for artifacts list
- Update `Artifact` type
> feat: artifacts list slot

- packages/web/src/utils/externalLinks.ts
> feat: add ci/cd overview link

- packages/web/src/components/molecules/ArtifactsList/ArtifactsList.styled.tsx
- packages/web/src/components/molecules/ArtifactsList/ArtifactsList.tsx
- packages/web/src/components/molecules/ArtifactsList/ArtifactsListItem.spec.tsx
- packages/web/src/components/organisms/EntityView/EntityView.tsx
- packages/web/src/components/organisms/ExecutionsTable/ExecutionsFilters/ExecutionsFilters.tsx
- packages/web/src/components/organisms/TestConfigurationForm/StringContentFields/StringContentFields.tsx
- packages/web/src/components/pages/Tests/TestDetails/TestExecution/TestExecutionArtifacts.tsx
- packages/web/src/models/artifact.ts
- packages/web/src/plugins/promo-banners/config.ts
- packages/web/src/plugins/tests-and-test-suites/plugin.tsx
- packages/web/src/utils/externalLinks.ts
- packages/web/src/utils/sources.ts
> Release Candidate v1.16.4

- packages/web/src/components/molecules/ArtifactsList/ArtifactsList.tsx
> fix: remove status check

- packages/web/src/services/tests.ts
> fix: executions request optional

- packages/web/src/components/molecules/ArtifactsList/ArtifactsList.tsx
- packages/web/src/services/tests.ts
> fixes for release v1.16.4

- packages/web/src/components/molecules/ArtifactsList/ArtifactsListItem.spec.tsx
- packages/web/src/services/artifacts.ts
- Refactor the way of downloading an artifact
- Previously opening a specific type of files in the browser instead of downloading them
> refactor: artifacts download service

- packages/web/src/components/molecules/ArtifactsList/ArtifactsListItem.spec.tsx
- packages/web/src/services/artifacts.ts
* refactor: artifacts download service
* fix: artifact download
* fix: test
* fix: download artifact/artifacts archive
This PR...
-
-
-
-
> refactor: artifacts download service (#1006)

- packages/web/src/utils/externalLinks.ts
> chore: add azure docs link

- packages/web/src/components/molecules/Console/Console.tsx
- packages/web/src/components/molecules/Console/LogProcessorLine.ts
- packages/web/src/store/logOutput.ts
- packages/web/src/styles/globalStyles.ts
> feat: logs store new data

- packages/web/src/components/molecules/ArtifactsList/ArtifactsListItem.spec.tsx
- packages/web/src/services/artifacts.ts
> fix: [TKC-1439] download artifact actual content

- packages/web/src/components/pages/Tests/TestDetails/TestSettings/SettingsVariables/Arguments.styled.tsx
- packages/web/src/components/pages/Tests/TestDetails/TestSettings/SettingsVariables/Arguments.tsx
- packages/web/src/models/execution.ts
- packages/web/src/services/executors.ts
> Release v1.16.6

- packages/web/src/components/pages/TestSuites/TestSuiteDetails/TestSuiteSettings/SettingsTests/SettingsTests.tsx
- packages/web/src/utils/externalLinks.ts
This PR...
- The wording of the dashboard for the Test Suites
-
-
-
> docs: test suite step docs link

- packages/web/src/utils/externalLinks.ts
This PR...
- updated link to test suite steps as they have been moved
-
-
-
> docs: [TKC-1579] update link to test suite steps #4

- .github/workflows/docker-build-beta-tag.yml
- .github/workflows/docker-build-tag.yml
This PR passes a tag with dispatch workflow to `testkube-dashboard-chart`.
-
-
-
-
> ci: add dispatch

- .github/workflows/docker-build-beta-tag.yml
- .github/workflows/docker-build-tag.yml
* add dispatch to CI workflow
This PR...
-
-
-
-
> ci: update flow

- .github/workflows/docker-build-beta-tag.yml
- .github/workflows/docker-build-tag.yml
- README.md
- packages/web/src/components/atoms/CreatableMultiSelect/CreatableMultiSelect.styled.tsx
- packages/web/src/components/atoms/CreatableMultiSelect/CreatableMultiSelect.tsx
- packages/web/src/components/molecules/LogOutput/LogOutput.tsx
- packages/web/src/components/molecules/LogOutput/LogOutputActions.tsx
- packages/web/src/components/molecules/LogOutput/LogOutputV1.tsx
- packages/web/src/components/molecules/LogOutput/LogOutputV2.styled.tsx
- packages/web/src/components/molecules/LogOutput/LogOutputV2.tsx
- packages/web/src/components/molecules/LogOutput/useLogsV2.ts
- packages/web/src/components/pages/TestSuites/TestSuiteDetails/TestSuiteSettings/SettingsTests/SettingsTests.tsx
- packages/web/src/index.tsx
- packages/web/src/styles/Colors.ts
- packages/web/src/utils/apiInfo.ts
- packages/web/src/utils/externalLinks.ts
> feat: logs v2

- .github/workflows/docker-build-beta-tag.yml
- .github/workflows/docker-build-tag.yml
- Dockerfile
- README.md
- nginx/nginx.conf
- packages/web/scripts/security.sh
- packages/web/src/components/atoms/CreatableMultiSelect/CreatableMultiSelect.styled.tsx
- packages/web/src/components/atoms/CreatableMultiSelect/CreatableMultiSelect.tsx
- packages/web/src/components/molecules/LogOutput/LogOutput.tsx
- packages/web/src/components/molecules/LogOutput/LogOutputActions.tsx
- packages/web/src/components/molecules/LogOutput/LogOutputV1.tsx
- packages/web/src/components/molecules/LogOutput/LogOutputV2.styled.tsx
- packages/web/src/components/molecules/LogOutput/LogOutputV2.tsx
- packages/web/src/components/molecules/LogOutput/useLogsV2.ts
- packages/web/src/components/pages/TestSuites/TestSuiteDetails/TestSuiteSettings/SettingsTests/SettingsTests.tsx
- packages/web/src/index.tsx
- packages/web/src/styles/Colors.ts
- packages/web/src/utils/apiInfo.ts
- packages/web/src/utils/externalLinks.ts
> bump version
